### ISSUE TITLE
FIS Error Message

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#140]
This was created with a strange workflow, so I'm not really sure what's going on.

Attempted to create an FIS error surface using slope and point density as usual and got the following extent union bug.

What's a little unusual is that I created the associated surfaces by browsing to them from an existing GCD project ,but that shouldn't really matter. The only thing I can think of is that the GCDConsoleLib slope or point density processes are produced rasters without proper spatial references. But I've added them both to ArcGIS and reviewed their spat ref and they look fine.

[DemoProject.zip](https://github.com/Riverscapes/gcd/files/1783044/DemoProject.zip)

Here's the project. The FIS inputs were:

```
D:\Testing\GCD\DemoProject\Inputs\Surveys\DEM0001\AssocSurfaces\Ass0001\SlopeDegrees.tif
D:\Testing\GCD\DemoProject\Inputs\Surveys\DEM0001\AssocSurfaces\Ass0002\PointDensity.tif
```

And here's the error:

```
Object reference not set to an instance of an object.
 --- Stacktrace --- 
   at GCDConsoleLib.ExtentRectangle.Union(ExtentRectangle rect) in D:\Code\gcd\gcd\GCDConsoleLib\ExtentRectangle.cs:line 169
   at GCDConsoleLib.Internal.BaseOperator`1.AddInputRaster(Raster rInput) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 111
   at GCDConsoleLib.Internal.BaseOperator`1._init(List`1 rRasters, List`1 rOutputRasters) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 148
   at GCDConsoleLib.Internal.BaseOperator`1..ctor(List`1 rRasters, List`1 rOutputRasters) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 93
   at GCDConsoleLib.Internal.CellByCellOperator`1..ctor(List`1 rRasters, List`1 rOutputRasters) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\CellByCellOperator.cs:line 22
   at GCDConsoleLib.Internal.Operators.FISRasterOp..ctor(Dictionary`2 rInputs, FileInfo fisFile) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\FISRasterOp.cs:line 34
   at GCDConsoleLib.Internal.Operators.CreateErrorRaster..ctor(Raster rawDEM, ErrorRasterProperties prop, Raster rOutputRaster) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\CreateErrorRaster.cs:line 42
   at GCDConsoleLib.RasterOperators.CreateErrorRaster(Raster rawDEM, ErrorRasterProperties props, FileInfo sOutputRaster, EventHandler`1 progressHandler) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 617
   at GCDCore.UserInterface.SurveyLibrary.ErrorSurfaces.frmSingleMethodError.cmdOK_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd\GCDCore\UserInterface\SurveyLibrary\ErrorSurfaces\frmSingleMethodError.cs:line 70
Windows: Microsoft Windows NT 6.2.9200.0
Date: 3/5/2018 3:46:21 PM
```

**Comment by MattReimer** [comment]
I can't reproduce this.

**Comment by philipbaileynar** [comment]
Unable to reproduce. Closing. It was a dubious workflow to start with...
