### ISSUE TITLE
Propagated Error Crashing on Multi Method

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#159]
When deriving a propagated error change detection, this exception was thrown:
```
Value was either too large or too small for a Decimal.
 --- Stacktrace --- 
   at System.Decimal..ctor(Double value)
   at GCDConsoleLib.GCD.DoDStats.get_NetVolumeOfDifference_Error() in D:\Code\gcd\gcd\GCDConsoleLib\GCD\DoDStatsMath.cs:line 29
   at GCDCore.Engines.EngineBase.GenerateChangeBarGraphicFiles(DirectoryInfo analysisFolder, DoDStats stats, Int32 fChartWidth, Int32 fChartHeight, String sFilePrefix) in D:\Code\gcd\gcd\GCDCore\Engines\EngineBase.cs:line 105
   at GCDCore.Engines.ChangeDetectionEngineBase.Calculate(String dodName, DirectoryInfo analysisFolder, Boolean bBuildPyramids, UnitGroup units) in D:\Code\gcd\gcd\GCDCore\Engines\DoD\ChangeDetectionBase.cs:line 79
   at GCDCore.UserInterface.ChangeDetection.frmDoDProperties.cmdOK_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd\GCDCore\UserInterface\ChangeDetection\frmDoDProperties.cs:line 95
Windows: Microsoft Windows NT 6.2.9200.0
Date: 3/9/2018 1:00:50 PM

```
I start out the video as if this is a tutorial video for [Multi Method](http://gcd.riverscapes.xyz/tutorials--how-to/workshop-tutorials/j_multimethoderror.html). THis is happening when using the Grand Canyon [dataset](http://etalweb.joewheaton.org/etal_workshops/GCD/2015_USU/J_ErrorEstimation.zip)
See video... https://youtu.be/k13PGvO0dBQ

**Comment by philipbaileynar** [comment]
I've reproduced this issue. The error is indeed on the line numbers mentioned in the trace statements reported by Joe. Here's a clean copy of the project that produces this error. 

Steps to reproduce:

1. Open the attached project
1. Perform Change Detection with Propagated Error Thresholding.

[gc_before_dod.zip](https://github.com/Riverscapes/gcd/files/1827307/gc_before_dod.zip)


And here's a picture of the reach:

![2018-03-19_162441](https://user-images.githubusercontent.com/8645379/37627624-8086822e-2b92-11e8-8684-d8a164551055.png)
