### ISSUE TITLE
Unable to delete a morphological analysis

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#205]
I was using GCD 7.0.10, and I performed a morphological analysis, and attempted to delete it from my project. The following handled exception was thrown:

```
deleting morphological analysis is not implemented.
 --- Stacktrace --- 
   at GCDCore.Project.Morphological.MorphologicalAnalysis.Delete() in D:\Code\gcd\gcd\GCDCore\Project\Morphological\MorphologicalAnalysis.cs:line 283
   at GCDCore.UserInterface.Project.TreeNodeTypes.TreeNodeItem.OnDelete(Object sender, EventArgs e) in D:\Code\gcd\gcd\GCDCore\UserInterface\Project\TreeNodeTypes\TreeNodeItem.cs:line 147
Windows: Microsoft Windows NT 6.2.9200.0
Date: 4/3/2018 2:34:05 PM
```

It looks like it actually deleted the information form the file folder `D:\0_GCD\GCD7.0.10\Rees\Analyses\CD\DoD0001\BS\BS0001\Morph\MA0001`, but it is still in the project. 
[Rees.gcd.txt](https://github.com/Riverscapes/gcd/files/1873277/Rees.gcd.txt)

**Comment by joewheaton** [comment]
@philipbaileynar you can use this ticket if you want (or ignore it). I used it to demonstrate to users how to report a problem. See http://gcd.riverscapes.xyz/Help/known-bugs.html

[GCD Project](https://drive.google.com/file/d/1OOcZBeE3TFKOFaLKh2l-rBsdeOQNV2-H/view?usp=sharing)

https://youtu.be/EFAQgvZQY0s
