### ISSUE TITLE
DoD the same raster and get an exception

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#212]
## The Problem

Add the same raster to a GCD project twice. You need to give each raster a different name, but essentially the same source raster is used for both. Performing a DoD on these two DEMs throws an exception. Regregttably, this is a realistic scenario when users click fast and forget to change the folder from which they are selecting their source rasters.

## Reproduction steps

1. Create new project.
2. Add first DEM
3. Add another DEM using the same source raster as the first.
4. Perform DoD (using any threshold method. I used MinLoD)

## Exception message

```text
D:\Testing\GCD\Self\Analyses\CD\DoD0001\tresh.tif, band 1: Failed to compute statistics, no valid pixels found in sampling.
 --- Stacktrace --- 
   at OSGeo.GDAL.Band.GetStatistics(Int32 approx_ok, Int32 force, Double& min, Double& max, Double& mean, Double& stddev)
   at GCDConsoleLib.Raster.GetStatistics() in D:\Code\gcd\gcd\GCDConsoleLib\Raster.cs:line 558
   at GCDConsoleLib.Histogram..ctor(Int32 bins, Raster rRa) in D:\Code\gcd\gcd\GCDConsoleLib\Histogram.cs:line 44
   at GCDConsoleLib.Internal.Operators.BinRaster..ctor(Raster rInput, Int32 numBins) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\BinRaster.cs:line 28
   at GCDConsoleLib.RasterOperators.BinRaster(Raster rInput, Int32 numberofBins) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 605
   at GCDCore.Engines.ChangeDetectionEngineBase.Calculate(String dodName, DirectoryInfo analysisFolder, Boolean bBuildPyramids, UnitGroup units) in D:\Code\gcd\gcd\GCDCore\Engines\DoD\ChangeDetectionBase.cs:line 72
   at GCDCore.UserInterface.ChangeDetection.frmDoDProperties.cmdOK_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd\GCDCore\UserInterface\ChangeDetection\frmDoDProperties.cs:line 95
 --- Exception Data --- 
GCD = 7.0.11.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 4/11/2018 2:47:10 PM
```

**Comment by philipbaileynar** [comment]
I've caught all the exceptions in the elevation change bar charts that are affected by there being no change. It's not pretty but it prevents the UI from choking.
