### ISSUE TITLE
Error Adding Profile Route to GCD Project

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#216]
## The Problem

When attempting to add a shapefile (in this case we know its wrong... it is missing both a spatial reference and has just one feature), we get an error that 'Error browsing to vector profile route`. This error goes away when a projection is added. So this tells us we just need to throw an exception for when a projection is not defined.

## Reproduction steps

Produced with Matt on GeoTERM River Dee project.

## Exception message

```text

------------------------------------------------
EXCEPTION
Error attempting to browse for vector GIS data source
 --- Stacktrace --- 
   at GCDAddIn.ArcMapBrowse.BrowseOpenVector(String formTitle, DirectoryInfo diWorkspace, String sFCName, BrowseGISTypes eType, IntPtr hParentWindowHandle) in D:\Code\gcd\gcd\GCDAddIn\ArcMapBrowse.cs:line 107
   at GCDAddIn.ucProjectManager.AddinImpl.OnGISBrowseVector(TextBox txt, PathEventArgs e, SimpleTypes geometryType) in D:\Code\gcd\gcd\GCDAddIn\ucProjectManager.cs:line 103
   at GCDCore.Project.ProjectManager.OnBrowseVector(TextBox txt, PathEventArgs e, SimpleTypes geometryType)
   at GCDCore.UserInterface.UtilityForms.ucVectorInput.cmdBrowse_Click(Object sender, PathEventArgs e)
 --- Exception Data --- 
ArcMap = 10.4.1.5686
GCD = 7.0.13.0Feature class is missing spatial reference
 --- Stacktrace --- 
   at GCDConsoleLib.Vector._load(Boolean leaveopen) in D:\Code\gcd\gcd\GCDConsoleLib\Vector.cs:line 442
   at GCDConsoleLib.Vector..ctor(FileInfo sFilename) in D:\Code\gcd\gcd\GCDConsoleLib\Vector.cs:line 36
   at GCDAddIn.ArcMapBrowse.BrowseOpenVector(String formTitle, DirectoryInfo diWorkspace, String sFCName, BrowseGISTypes eType, IntPtr hParentWindowHandle) in D:\Code\gcd\gcd\GCDAddIn\ArcMapBrowse.cs:line 102
 --- Exception Data --- 
Path = C:\0_GCD\GeoTERM\CaseStudies\SEPA\Vector\Dee_Centreline.shp
Windows: Microsoft Windows NT 6.2.9200.0
Date: 4/16/2018 10:25:03 AM

```

## Anything else?

You can attach links to datasets.

**Comment by MattReimer** [comment]
This is part of the ongoing problems we've been having with projection issues. I'm on it but it might be a week or so until I get this solved.

**Comment by MattReimer** [comment]
I'm pretty sure 923fb8d5c495d5febe67cb1683b45de7a5c1aa84 fixes this but I don't have the precise dataset to reproduce so I'm just going to close it and we can re-open if it remains an issue.
