### ISSUE TITLE
Minor Issues with Cross Section Explorer - And Reporting how it Did

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#223]
## The Problem
- NEED version number!!!! THIS IS NOT 1.0.0.0. Very difficult to know what we're in (see https://youtu.be/keipOG0IRUE for example)
![versionwrong](https://user-images.githubusercontent.com/9723905/38873637-7ea05af6-4213-11e8-90e9-d5e3f677a4b6.png)
- Can create database, but it has having trouble opening database in Cross Section Viewer. 
- Warning for above is confusing:
![erroropening](https://user-images.githubusercontent.com/9723905/38873428-fc28509c-4212-11e8-94a9-dc9c1e3fb44a.png)
Error would be more accurate to say that it can't 

For this and to see how this is doing:
https://youtu.be/Ew2hkhOANNU

Its working petty well overall. Really cool patterns!

Minor error on Surface Difference Plot, where it throws an exception when attempting to view an empty cross section (i.e. exists in shapefile, but not in DEM/DoD domain:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at CrossSectionViewer.Tools.frmSurfaceDelta.LoadChart(Survey newSurvey, Survey oldSurvey, CrossSection xs)
   at CrossSectionViewer.Tools.frmSurfaceDelta.lstCrossSections_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
CrossSectionViewer
    Assembly Version: 2.0.3.0
    Win32 Version: 2.0.3.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/Apps/2.0/L96CZOP4.AX2/PA1PP15M.01T/cros..tion_d2a9a24e25080d83_0001.0000_601859eb168ea003/CrossSectionViewer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

...
```

**Comment by philipbaileynar** [comment]
The Cross Section Viewer started displaying the correct version in the last release. Leaving ticket open for other items...
