### ISSUE TITLE
Test GCD 7.0.15 for relaxing Projection - Works for Mask Library - Crashes on Budget Seg

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#227]
## The Problem
Warning comes up when adding to mask library... lets me get through and add. However, when I attempt to perform budget segregation, it fails another check (see messages below and video).
https://youtu.be/vZYpZjXMANU

## Reproduction steps

1. I did this on `C:\0_GCD\GeoTERM\CaseStudies\SEPA` dataset
2. I opened up this GCD Project: [Dee](https://usu.box.com/s/q243dpf14fbh6e71es3xlij6kk5czbrg)

## Exception message (First) on adding to budget seg:

```text

No PROJ.4 translation for destination SRS, coordinate transformation initialization has failed.
 --- Stacktrace --- 
   at OSGeo.GDAL.Gdal.RasterizeLayer(Dataset dataset, Int32 bands, Int32[] band_list, Layer layer, IntPtr pfnTransformer, IntPtr pTransformArg, Int32 burn_values, Double[] burn_values_list, String[] options, GDALProgressFuncDelegate callback, String callback_data)
   at GCDConsoleLib.VectorRaster.Rasterize(Vector vectorinput, Raster outputRaster) in D:\Code\gcd\gcd\GCDConsoleLib\VectorRaster.cs:line 88
   at GCDConsoleLib.VectorRaster..ctor(Raster Template, Vector vectorInput, String FieldName) in D:\Code\gcd\gcd\GCDConsoleLib\VectorRaster.cs:line 47
   at GCDConsoleLib.RasterOperators.GetStatsMinLoD(Raster rawDoD, Decimal minLoD, Vector PolygonMask, String FieldName, UnitGroup units, Boolean RasterizeFirst) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 393
   at GCDCore.Engines.BudgetSegregationEngine.Calculate(String dodName, DirectoryInfo analysisFolder, DoDBase dod, AttributeFieldMask mask)
   at GCDCore.UserInterface.BudgetSegregation.frmBudgetSegProperties.cmdOK_Click(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.4.1.5686
GCD = 7.0.15.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 4/17/2018 9:41:47 AM

```
Next Error Message:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at GCDCore.UserInterface.BudgetSegregation.frmBudgetSegResults..ctor(BudgetSegregation BS)
   at GCDCore.UserInterface.Project.TreeNodeTypes.DoDGroup.OnAdd(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ESRI.DADF.Core
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.DADF.Core.DLL
----------------------------------------
ESRI.APWR.ApFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 10.2.0.7
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/ESRI.APWR.ApFramework/1.0.0.0__0e46c6306d55f57a/ESRI.APWR.ApFramework.dll
----------------------------------------
ESRI.ArcGIS.System
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.System/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.System.dll
----------------------------------------
ESRI.ArcGIS.Display
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Display/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Display.dll
----------------------------------------
ESRI.ArcGIS.Carto
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Carto/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Carto.dll
----------------------------------------
ESRI.ArcGIS.Geodatabase
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Geodatabase/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Geodatabase.dll
----------------------------------------
ESRI.ArcGIS.Geometry
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Geometry/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Geometry.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
ESRI.ArcGIS.Desktop.AddIns.Factory
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.Desktop.AddIns.Factory.DLL
----------------------------------------
ESRI.ArcGIS.Desktop.AddIns
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.Desktop.AddIns.DLL
----------------------------------------
ESRI.ArcGIS.Framework
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Framework/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Framework.dll
----------------------------------------
ESRI.ArcGIS.ArcMapUI
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.ArcMapUI/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.ArcMapUI.dll
----------------------------------------
GCDAddIn
    Assembly Version: 7.0.15.0
    Win32 Version: 7.0.15.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/GCDAddIn.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
GCDCore
    Assembly Version: 7.0.15.0
    Win32 Version: 7.0.15.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/GCDCore.DLL
----------------------------------------
naru
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/naru.DLL
----------------------------------------
GCDAddIn
    Assembly Version: 6.1.14.0
    Win32 Version: 6.1.14.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7B0BF5B57C-9CFA-40F2-B0D3-B55EFC0738E8%7D/GCDAddIn.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
ESRI.ArcGIS.Geoprocessor
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Geoprocessor/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Geoprocessor.dll
----------------------------------------
ESRI.ArcGIS.Geoprocessing
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Geoprocessing/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Geoprocessing.dll
----------------------------------------
ESRI.ArcGIS.DataManagementTools
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.DataManagementTools/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.DataManagementTools.dll
----------------------------------------
GpMetadataFunctions
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/GpMetadataFunctions.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
ESRI.ArcGIS.SearchUI
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.SearchUI.DLL
----------------------------------------
ESRI.ArcGIS.SearchControl
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.SearchControl.DLL
----------------------------------------
ESRI.ArcGIS.SearchCore
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.SearchCore.DLL
----------------------------------------
ESRI.ArcGIS.Search
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Search/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Search.dll
----------------------------------------
ESRI.ArcGIS.SystemUI
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.SystemUI/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.SystemUI.dll
----------------------------------------
ESRI.ArcGIS.Version
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Version/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Version.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data.SqlXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
System.Xml.Xsl.CompiledQuery.1
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
Lucene.Net
    Assembly Version: 2.9.2.1
    Win32 Version: 2.9.2.1
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Lucene.Net/2.9.2.1__402f1553d5c332e7/Lucene.Net.dll
----------------------------------------
Snowball.Net
    Assembly Version: 2.0.0.1
    Win32 Version: 2.0.0.1
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Snowball.Net/2.0.0.1__402f1553d5c332e7/Snowball.Net.dll
----------------------------------------
ESRI.ArcGIS.MxCommands
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.MxCommands.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
ESRI.ArcGIS.MapCenter
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7B75701328-F0CC-4E65-B204-99944EDF5B93%7D/ESRI.ArcGIS.MapCenter.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
ESRI.ArcGIS.ArcGlobe
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.ArcGlobe/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.ArcGlobe.dll
----------------------------------------
ESRI.ArcGIS.ArcScene
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.ArcScene/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.ArcScene.dll
----------------------------------------
ESRI.ArcGIS.Editor
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Editor/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Editor.dll
----------------------------------------
UnitsNet
    Assembly Version: 3.77.0.0
    Win32 Version: 3.77.0.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/UnitsNet.DLL
----------------------------------------
GCDConsoleLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/GCDConsoleLib.DLL
----------------------------------------
ESRI.ArcGIS.DataSourcesRaster
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.DataSourcesRaster/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.DataSourcesRaster.dll
----------------------------------------
gdal_csharp
    Assembly Version: 1.0.6439.40988
    Win32 Version: 1.0.6439.40988
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/gdal_csharp.DLL
----------------------------------------
ESRI.ArcGIS.CatalogUI
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.CatalogUI/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.CatalogUI.dll
----------------------------------------
ESRI.ArcGIS.Catalog
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Catalog/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Catalog.dll
----------------------------------------
ogr_csharp
    Assembly Version: 1.0.6439.40987
    Win32 Version: 1.0.6439.40987
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/ogr_csharp.DLL
----------------------------------------
osr_csharp
    Assembly Version: 1.0.6439.40986
    Win32 Version: 1.0.6439.40986
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/osr_csharp.DLL
----------------------------------------
ESRI.ArcGIS.ReportWriter
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.ReportWriter.DLL
----------------------------------------
ESRI.ArcGIS.ReportWriter.Core
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.ReportWriter.Core.DLL
----------------------------------------
ESRI.APWR.ApUniqueIDMgrExt
    Assembly Version: 1.0.0.0
    Win32 Version: 10.2.0.7
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/ESRI.APWR.ApUniqueIDMgrExt/1.0.0.0__78a748607336c22a/ESRI.APWR.ApUniqueIDMgrExt.dll
----------------------------------------
ESRI.APWR.ApUniqueIDMgr
    Assembly Version: 1.0.0.0
    Win32 Version: 10.2.0.7
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/ESRI.APWR.ApUniqueIDMgr/1.0.0.0__f5a12bb239ee939e/ESRI.APWR.ApUniqueIDMgr.dll
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```
## Anything else?

You can attach links to datasets.

**Comment by MattReimer** [comment]
This problem is going to be (potentially) a LOT harder to fix because what GDAL is telling us here is "I have no way to rasterize this vector into the projection you're asking me to use".

We can investigate using the input Vector projection instead of the one from the template raster but I'm a bit worried this might come with its own baggage.

**Comment by joewheaton** [comment]
Some good news... silver lining:
When I test the adding of Linear Profile from a shapefile with screwed up projection, it lets me get away with it, and it correctly calculates profile and opens in cross section explorer (note that I am NOT getting same #223 issue with the inability to open it this time).  For your viewing pleasure/boredom:
https://youtu.be/RFXf_ZL18Js

**Comment by MattReimer** [comment]
The fix for this is a bit too risky to test properly with 1 day's notice. We've got enough that we can push through the demo tomorrow so let's push this issue until after the demo:

Here's how it's going to go down though (warning, not complete!!!):

```diff
diff --git a/GCDConsoleLib/GISDataset.cs b/GCDConsoleLib/GISDataset.cs
index 47f408a..6df1777 100644
--- a/GCDConsoleLib/GISDataset.cs
+++ b/GCDConsoleLib/GISDataset.cs
@@ -37,6 +37,7 @@ namespace GCDConsoleLib
         public abstract void Copy(FileInfo destPath);
         public abstract void Delete();
         public abstract void UnloadDS();
+        public abstract void SetProjection(bool leaveopen);
         protected abstract void _initfromfile();
 
         /// <summary>
diff --git a/GCDConsoleLib/Raster.cs b/GCDConsoleLib/Raster.cs
index bee6169..ea9cffd 100644
--- a/GCDConsoleLib/Raster.cs
+++ b/GCDConsoleLib/Raster.cs
@@ -246,6 +246,13 @@ namespace GCDConsoleLib
             UnloadDS();
         }
 
+        public override void SetProjection(Projection newProj)
+        {
+            Open(true);
+            _ds.SetProjection(newProj.OriginalString);
+            UnloadDS();
+        }
+
         /// <summary>
         /// Handy unit convertor
         /// </summary>
diff --git a/GCDConsoleLib/Vector.cs b/GCDConsoleLib/Vector.cs
index 540af34..bb1dc10 100644
--- a/GCDConsoleLib/Vector.cs
+++ b/GCDConsoleLib/Vector.cs
@@ -116,6 +116,13 @@ namespace GCDConsoleLib
             //}
         }
 
+        public override void SetProjection()
+        {
+            Open();
+            Layer mLayer = _ds.GetLayerByIndex(0);
+            mLayer.Set
+        }
+
         /// <summary>
         /// Copy the vector somewhere else
         /// </summary>
diff --git a/GCDConsoleLib/VectorRaster.cs b/GCDConsoleLib/VectorRaster.cs
index a6e962c..40b57cf 100644
--- a/GCDConsoleLib/VectorRaster.cs
+++ b/GCDConsoleLib/VectorRaster.cs
@@ -78,6 +78,7 @@ namespace GCDConsoleLib
             Dataset _ds = Gdal.Open(outputRaster.GISFileInfo.FullName, Access.GA_Update);
 
             vectorinput.Open();
+            _ds.SetProjection(vectorinput.Proj.OriginalString);
 
             int[] bandlist = new int[] { 1 };
             OSGeo.OGR.Layer layer = vectorinput._ds.GetLayerByIndex(0);
diff --git a/GCDCore/UserInterface/SurveyLibrary/GISDatasetValidation.cs b/GCDCore/UserInterface/SurveyLibrary/GISDatasetValidation.cs
index 16c442b..a92e4fa 100644
--- a/GCDCore/UserInterface/SurveyLibrary/GISDatasetValidation.cs
+++ b/GCDCore/UserInterface/SurveyLibrary/GISDatasetValidation.cs
@@ -13,9 +13,26 @@ namespace GCDCore.UserInterface.SurveyLibrary
     {
         public static bool ValidateRaster(Raster raster)
         {
-            if (!ValidateSpatialReference(raster, "raster", "rasters"))
+            try
+            {
+                if (!ValidateSpatialReference(raster, "raster", "rasters"))
+                {
+                    // Get the reference projection for the project (if the project exists and has at least one GIS dataset)
+                    Projection referenceProjection = null;
+                    if (ProjectManager.Project != null)
+                    {
+                        referenceProjection = ProjectManager.Project.ReferenceProjection;
+                        raster.SetProjection(referenceProjection);
+                    }
+                    else
+                        return false;
+          
+                }
+            }
+            catch (ArgumentException)
+            {
                 return false;
-
+            }
 
             return true;
         }
@@ -56,7 +73,7 @@ namespace GCDCore.UserInterface.SurveyLibrary
                 }
 
                 MessageBox.Show(msg, Properties.Resources.ApplicationNameLong, MessageBoxButtons.OK, MessageBoxIcon.Information);
-                return false;
+                throw new ArgumentException("Unknown projection found");
             }
 
             //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
@@ -74,6 +91,8 @@ namespace GCDCore.UserInterface.SurveyLibrary
                 DialogResult result = MessageBox.Show(msg, Properties.Resources.ApplicationNameLong, MessageBoxButtons.YesNo, MessageBoxIcon.Warning, MessageBoxDefaultButton.Button2);
 
                 if (result == DialogResult.No)
+                    throw new ArgumentException("Projections do not match");
+                else
                     return false;
             }
 
@@ -90,6 +109,8 @@ namespace GCDCore.UserInterface.SurveyLibrary
                 DialogResult result = MessageBox.Show(msg, "HorizontalUnits Mismatch", MessageBoxButtons.YesNo, MessageBoxIcon.Warning, MessageBoxDefaultButton.Button2);
 
                 if (result == DialogResult.No)
+                    throw new ArgumentException("Projection horizontal unit does not match");
+                else
                     return false;
 
             }
```

**Comment by joewheaton** [comment]
This is working really nice now. This tested well:
https://youtu.be/hzepiR2XjKw

Two minor requests (feel free to assign this to Future Requests milestone):
1. Change symbol for directional Budget Segregation in Tree to: 
![maskdirectional_icon](https://user-images.githubusercontent.com/9723905/39786850-b2473b7c-52df-11e8-902c-2254894734ef.png) Maybe with Blue and Red fill or something....
2. Sort the list in the Budget Seg form for directional mask by the Typology (just like you do in subsequent morphological analysis.
And a reminder of James request to add to the directional mask (#194)
![2018-05-08_165006](https://user-images.githubusercontent.com/9723905/39786927-ff231eac-52df-11e8-959d-4943d33bd494.png)
