### ISSUE TITLE
Potential NoData Error on FIS Error Surface Derivation

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#229]
## The Problem

When deriving an FIS error surface, I have a problem with an exception being thrown when it tries to add this to the map. I've seen two behaviors:
1. Throws exception message below when trying to add raster to map. If you look in folder, file exists, and can be manually  added, but doesn't display properly (you can fix this by importing symbology from another dataset):
![fis_nodata](https://user-images.githubusercontent.com/9723905/38885016-b1b3bd28-422e-11e8-9c7b-bacd574f25f3.png)
2.  It says 'raster produced successfully' but adds an empty raster to map. When you got and add it to map, it has same display issues.

I can't tell if this is a problem with the calculation of statistics, or the actual NoData values saved in the raster.

See here:  https://youtu.be/TnnQ7ugmEO4?t=13m6s (*I just noticed that it sounds like I'm talking with a lisp... I'm using a Bose set of headphones and not my normal headset... I wonder if the Bluetooth and frequency of audio is just doing something off... anyhow kind of funny, but also choppy.*)

## Reproduction steps

1. From the [Feshie](https://s3-us-west-2.amazonaws.com/etalweb.joewheaton.org/GCD/GCD7/Tutorials/V_BudgetSeg.zip) data, use `2005DEM`, and derive Associated Surfaces of `Slope Degrees` from DEM and `PointDensity` from `SurveyFile`, and load `PQ2005` for 3D Point Quality.
2. Derive an FIS error surface using `GPSZErrorPDSLPdegPQ.fis` in FIS folder.

## Exception message

```text

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Decimal..ctor(Double value)
   at GCDConsoleLib.Raster.GetStatistics() in D:\Code\gcd\gcd\GCDConsoleLib\Raster.cs:line 559
   at GCDAddIn.GCDArcMapManager.AddErrSurface(ErrorSurface errRow) in D:\Code\gcd\gcd\GCDAddIn\GCDArcMapManager.cs:line 301
   at GCDAddIn.ucProjectManager.AddinImpl.OnAddRasterToMap(GCDProjectRasterItem raster) in D:\Code\gcd\gcd\GCDAddIn\ucProjectManager.cs:line 150
   at GCDCore.Project.ProjectManager.OnAddRasterToMap(GCDProjectRasterItem raster)
   at GCDCore.UserInterface.Project.TreeNodeTypes.TreeNodeItem.OnAddToMap(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ESRI.DADF.Core
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.DADF.Core.DLL
----------------------------------------
ESRI.APWR.ApFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 10.2.0.7
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/ESRI.APWR.ApFramework/1.0.0.0__0e46c6306d55f57a/ESRI.APWR.ApFramework.dll
----------------------------------------
ESRI.ArcGIS.System
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.System/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.System.dll
----------------------------------------
ESRI.ArcGIS.Display
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Display/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Display.dll
----------------------------------------
ESRI.ArcGIS.Carto
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Carto/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Carto.dll
----------------------------------------
ESRI.ArcGIS.Geodatabase
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Geodatabase/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Geodatabase.dll
----------------------------------------
ESRI.ArcGIS.Geometry
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Geometry/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Geometry.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
ESRI.ArcGIS.Desktop.AddIns.Factory
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.Desktop.AddIns.Factory.DLL
----------------------------------------
ESRI.ArcGIS.Desktop.AddIns
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.Desktop.AddIns.DLL
----------------------------------------
ESRI.ArcGIS.Framework
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Framework/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Framework.dll
----------------------------------------
ESRI.ArcGIS.ArcMapUI
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.ArcMapUI/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.ArcMapUI.dll
----------------------------------------
GCDAddIn
    Assembly Version: 7.0.15.0
    Win32 Version: 7.0.15.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/GCDAddIn.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
GCDCore
    Assembly Version: 7.0.15.0
    Win32 Version: 7.0.15.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/GCDCore.DLL
----------------------------------------
naru
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/naru.DLL
----------------------------------------
GCDAddIn
    Assembly Version: 6.1.14.0
    Win32 Version: 6.1.14.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7B0BF5B57C-9CFA-40F2-B0D3-B55EFC0738E8%7D/GCDAddIn.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
ESRI.ArcGIS.Geoprocessor
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Geoprocessor/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Geoprocessor.dll
----------------------------------------
ESRI.ArcGIS.Geoprocessing
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Geoprocessing/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Geoprocessing.dll
----------------------------------------
ESRI.ArcGIS.DataManagementTools
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.DataManagementTools/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.DataManagementTools.dll
----------------------------------------
GpMetadataFunctions
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/GpMetadataFunctions.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
ESRI.ArcGIS.SearchUI
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.SearchUI.DLL
----------------------------------------
ESRI.ArcGIS.SearchControl
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.SearchControl.DLL
----------------------------------------
ESRI.ArcGIS.SearchCore
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.SearchCore.DLL
----------------------------------------
ESRI.ArcGIS.Search
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Search/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Search.dll
----------------------------------------
ESRI.ArcGIS.SystemUI
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.SystemUI/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.SystemUI.dll
----------------------------------------
ESRI.ArcGIS.Version
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Version/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Version.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Data.SqlXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
System.Xml.Xsl.CompiledQuery.1
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
Lucene.Net
    Assembly Version: 2.9.2.1
    Win32 Version: 2.9.2.1
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Lucene.Net/2.9.2.1__402f1553d5c332e7/Lucene.Net.dll
----------------------------------------
Snowball.Net
    Assembly Version: 2.0.0.1
    Win32 Version: 2.0.0.1
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Snowball.Net/2.0.0.1__402f1553d5c332e7/Snowball.Net.dll
----------------------------------------
ESRI.ArcGIS.MxCommands
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.MxCommands.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
ESRI.ArcGIS.MapCenter
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7B75701328-F0CC-4E65-B204-99944EDF5B93%7D/ESRI.ArcGIS.MapCenter.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
ESRI.ArcGIS.ArcGlobe
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.ArcGlobe/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.ArcGlobe.dll
----------------------------------------
ESRI.ArcGIS.ArcScene
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.ArcScene/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.ArcScene.dll
----------------------------------------
ESRI.ArcGIS.Editor
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Editor/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Editor.dll
----------------------------------------
UnitsNet
    Assembly Version: 3.77.0.0
    Win32 Version: 3.77.0.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/UnitsNet.DLL
----------------------------------------
GCDConsoleLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/GCDConsoleLib.DLL
----------------------------------------
ogr_csharp
    Assembly Version: 1.0.6439.40987
    Win32 Version: 1.0.6439.40987
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/ogr_csharp.DLL
----------------------------------------
osr_csharp
    Assembly Version: 1.0.6439.40986
    Win32 Version: 1.0.6439.40986
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/osr_csharp.DLL
----------------------------------------
gdal_csharp
    Assembly Version: 1.0.6439.40988
    Win32 Version: 1.0.6439.40988
    CodeBase: file:///C:/Users/JoeWh/AppData/Local/ESRI/Desktop10.4/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/gdal_csharp.DLL
----------------------------------------
ESRI.ArcGIS.DataSourcesRaster
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.DataSourcesRaster/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.DataSourcesRaster.dll
----------------------------------------
ESRI.ArcGIS.DataSourcesFile
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.DataSourcesFile/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.DataSourcesFile.dll
----------------------------------------
ESRI.ArcGIS.CatalogUI
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.CatalogUI/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.CatalogUI.dll
----------------------------------------
ESRI.ArcGIS.Catalog
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Catalog/v4.0_10.4.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Catalog.dll
----------------------------------------
ESRI.ArcGIS.ReportWriter
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.ReportWriter.DLL
----------------------------------------
ESRI.ArcGIS.ReportWriter.Core
    Assembly Version: 10.4.0.0
    Win32 Version: 10.4.1.5686
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.4/bin/ESRI.ArcGIS.ReportWriter.Core.DLL
----------------------------------------
ESRI.APWR.ApUniqueIDMgrExt
    Assembly Version: 1.0.0.0
    Win32 Version: 10.2.0.7
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/ESRI.APWR.ApUniqueIDMgrExt/1.0.0.0__78a748607336c22a/ESRI.APWR.ApUniqueIDMgrExt.dll
----------------------------------------
ESRI.APWR.ApUniqueIDMgr
    Assembly Version: 1.0.0.0
    Win32 Version: 10.2.0.7
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/ESRI.APWR.ApUniqueIDMgr/1.0.0.0__f5a12bb239ee939e/ESRI.APWR.ApUniqueIDMgr.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by MattReimer** [comment]
The issue is withe PQ 2005 and occurs at the edges. An interesting aside is that this raster has stats set really messes with QGis and causes it to crash.

but I digress: we were talking about edge effects:

<img width="956" alt="screen shot 2018-04-17 at 7 36 57 pm" src="https://user-images.githubusercontent.com/1063391/38889525-e4859d32-4276-11e8-947e-ca273acd797b.png">

The issue is that the PQ 2005 raster's `nodata` value is set incorrectly:

```
-3.40282e+38 (nodata value for the raster)
-3.40282347e+38 (value in each Nodata cell
```

The workaround for the workshop is to setnull on the `PQ_2005` before you use it so the NDV gets set properly. After that you shouldn't have this issue. 

That being said we **absolutely should fail more gracefully than this**.

**Comment by joewheaton** [comment]
I like the idea of **failing more gracefully**. I will aspire to such heights in all my future failures.
