### ISSUE TITLE
Errors with Tools -> Options ->Survey Types

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/gcd#246]
## The Problem

There are a bunch of problems with this form. There seems to be an error where it can't find the `SurveyTypes.xml` (see error below)

Also @joewheaton noticed that these values aren't plumbed into the error form as the defaults. 

It's probably a case of where we just haven't looked into it yet. 

## Exception message

```text
Could not find a part of the path 'C:\Users\Administrator\AppData\Roaming\GCD\SurveyTypes.xml'.
 --- Stacktrace --- 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Xml.XmlDocument.Save(String filename)
   at GCDCore.Project.SurveyType.Save(FileInfo filePath, Dictionary`2 dSurveyTypes) in C:\dev\gcd\GCDCore\Project\SurveyType.cs:line 94
   at GCDCore.Project.ProjectManager.set_SurveyTypes(Dictionary`2 value) in C:\dev\gcd\GCDCore\Project\ProjectManager.cs:line 53
   at GCDCore.UserInterface.Options.frmOptions.btnOK_Click(Object sender, EventArgs e) in C:\dev\gcd\GCDCore\UserInterface\frmOptions.cs:line 165
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
```

**Comment by philipbaileynar** [comment]
The missing plumbing of survey type error values is already tracked as issue #181

**Comment by philipbaileynar** [comment]
The missing plumbing of survey type error values is already tracked as issue #181
