### ISSUE TITLE
GCD7 derive error surface

### ISSUE THREAD

**Issue by jb10016** [Riverscapes/gcd#27]
@philipbaileynar 

On equal GCD6 and GCD7 projects, using the same data with close to identical data paths, receive this error:

```
TopologyException: side location conflict at 1236570.5000000019 5031485.0000000019
 --- Stacktrace --- 
   at OSGeo.OGR.Geometry.Contains(Geometry other)
   at GCDConsoleLib.Vector.ShapesContainPoint(Double x, Double y, String fieldName) in D:\Code\gcd\gcd\GCDConsoleLib\Vector.cs:line 118
   at GCDConsoleLib.Internal.Operators.CreateErrorRaster.CellOp(List`1 data, List`1 outputs, Int32 id) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\CreateErrorRaster.cs:line 149
   at GCDConsoleLib.Internal.CellByCellOperator`1.ChunkOp(List`1 data, List`1 outChunks) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\CellByCellOperator.cs:line 32
   at GCDConsoleLib.Internal.BaseOperator`1.Run() in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 304
   at GCDConsoleLib.RasterOperators.CreateErrorRaster(Raster rawDEM, Vector PolygonMask, String MaskFieldName, Dictionary`2 props, FileInfo sOutputRaster, EventHandler`1 progressHandler) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 446
   at GCDCore.UserInterface.SurveyLibrary.frmErrorSurfaceProperties.btnOK_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd\GCDCore\UserInterface\SurveyLibrary\frmErrorSurfaceProperties.cs:line 664
Windows: Microsoft Windows NT 6.2.9200.0
Date: 26/01/2018 15:41:07
```
Followed by:

```
Error Calculating Error Surface
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
 --- Stacktrace --- 
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   at GCDCore.UserInterface.SurveyLibrary.frmDEMSurveyProperties.cmdCalculateErrorSurface_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd\GCDCore\UserInterface\SurveyLibrary\frmDEMSurveyProperties.cs:line 491
Windows: Microsoft Windows NT 6.2.9200.0
Date: 26/01/2018 15:45:29
```

on **the derivation of a multimethod error surface.**  Works fine in GCD6

**Comment by philipbaileynar** [comment]
@jb10016 can you zip up the polygon ShapeFile and attach to this issue please?

Do you have overlapping polygons?

**Comment by jb10016** [comment]
@philipbaileynar 

I don't think so, but that was my thought too, though I have the same problem with two separate examples.  

The shapefiles work in GCD6, but not 7 and I moved the test case down to a folder close to the root to isolate any issue there.  I've added the DEM and associated shapefile mask to the attached zip
[Uploading Event_08.zip…]

**Comment by joewheaton** [comment]
Even if we did, it worked in GCD 6... 

How do you check for or enforce overlapping polygons? If you insist on enforcing such things, we need to provide better guidance to the user in the tool that this is a requirement.

**Comment by philipbaileynar** [comment]
The underlying methodology that we are using is now completely different. In early versions of GCD 7 we were trying to compare the vector polygons and raster cells to perform certain operations. We have abandoned this approach because the performance was terrible (as observed by @jb10016 in budget segregation). We are now using GDAL to rastersize the polygons. Not only is the rastersization extremely fast, but then comparing the rastersized mask with the underlying DEM raster becomes simple raster math (which should also be extremely quick).

All this to say... the underlying code is now radically different. @jb10016 please re-test with 7.0.05 or greater once you get it.

**Comment by philipbaileynar** [comment]
Closing as we have fixed lots of issues with error surface generation and also re-implemented the user interface from scratch.
