### ISSUE TITLE
Edit Linear Extraction Error

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#273]
## The Problem

When attempting to edit a linear extraction, an unhandled exception is thrown (see below).
![linearextraction_edit](https://user-images.githubusercontent.com/9723905/39675351-26f41028-5117-11e8-87fb-e541e87bd9b0.png)
## Reproduction steps

1.Calculate linear extraction of DEM
2. Attempt to edit properties

This brings up a related question, why do some exceptions have the handy little link to GitHub and copy to clipboard, and some (like this do not)?

## Exception message

```text

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NotImplementedException: Unhandled editing of project type
   at GCDCore.UserInterface.Project.TreeNodeTypes.TreeNodeItem.OnEdit(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ESRI.DADF.Core
    Assembly Version: 10.5.0.0
    Win32 Version: 10.5.1.7333
    CodeBase: file:///D:/ProgramFiles/ArcGIS/Desktop10.5/bin/ESRI.DADF.Core.DLL
----------------------------------------
ESRI.ArcGIS.Desktop.AddIns.Factory
    Assembly Version: 10.5.0.0
    Win32 Version: 10.5.1.7333
    CodeBase: file:///D:/ProgramFiles/ArcGIS/Desktop10.5/bin/ESRI.ArcGIS.Desktop.AddIns.Factory.DLL
----------------------------------------
ESRI.ArcGIS.Desktop.AddIns
    Assembly Version: 10.5.0.0
    Win32 Version: 10.5.1.7333
    CodeBase: file:///D:/ProgramFiles/ArcGIS/Desktop10.5/bin/ESRI.ArcGIS.Desktop.AddIns.DLL

....
```

**Comment by MattReimer** [comment]
I've got a fix stashed. Talk to @philipbaileynar about why it's not quite working.

**Comment by joewheaton** [comment]
Tested... seems fixed. I can edit: See first part of:
https://youtu.be/7d6RnMWcso0
