### ISSUE TITLE
Error with adding Existing DEM Survey: Attempted to divide by zero

### ISSUE THREAD

**Issue by mjcashman** [Riverscapes/gcd#284]
When I attempt to add an existing DEM (SfM-derived) to the GCD project, when I add the original data under the original raster I get the error message: "Attempted to Divide by Zero"

What do I need to do to get around this? Or is this something particular to GCD? The DEM loads into Arc and other GIS software without issue.

Exception message is below:

Attempted to divide by zero.
 --- Stacktrace --- 
   at System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
   at GCDConsoleLib.ExtentRectangle.GetDivisibleExtent() in D:\Code\gcd\gcd\GCDConsoleLib\ExtentRectangle.cs:line 376
   at GCDCore.UserInterface.SurveyLibrary.ExtentImporter.Initialize(Decimal cellWidth)
   at GCDCore.UserInterface.SurveyLibrary.ExtentImporter.set_InputExtent(ExtentRectangle value)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.OnRasterChanged(Object sender, PathEventArgs e)
 --- Exception Data --- 
ArcMap = 10.5.1.7333
GCD = 7.1.0.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 23-May-18 2:14:25 PM

**Comment by mjcashman** [comment]
Hi Phillip,

Thanks for your quick reply. I think I (also) may have a concurrency issue
right now, so let me resolve that first. If I still have a problem after I
fix that, I'll let you know and send the information or data next.

Best,
Matthew

******************************************
Matthew J Cashman, PhD
Hydrologist/Geomorphologist
United States Geological Survey
MD/DE/DC Water Science Center
mcashman@usgs.gov
(443) 498-5511
******************************************
