### ISSUE TITLE
Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))

### ISSUE THREAD

**Issue by nanaesri** [Riverscapes/gcd#289]
When I try to open the GCD project explorer this error appears.

## Reproduction steps

1. I installed the ext... no problem
2. Open ArcMap and the toolbar shows... no problem

## Exception message
Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
 --- Stacktrace --- 
   at ESRI.ArcGIS.Framework.IDockableWindowManager.GetDockableWindow(UID dockWnd)
   at GCDAddIn.Project.btnProjectExplorer.ShowProjectExplorer(Boolean bVisible) in D:\Code\gcd\gcd\GCDAddIn\Project\btnProjectExplorer.cs:line 38
   at GCDAddIn.Project.btnProjectExplorer.OnClick() in D:\Code\gcd\gcd\GCDAddIn\Project\btnProjectExplorer.cs:line 15
 --- Exception Data --- 
ArcMap = 10.5.0.6491
GCD = 7.1.0.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 6/16/2018 8:40:26 PM

Paste the exception message you are getting from the app here. It really helps us. 

```

Thanks in advance.

**Comment by joewheaton** [comment]
Thanks @nanaesri and sorry this isn't working. Any chance you could provide a link to the dataset and/or post a YouTube video of what's happening. @MattReimer and @philipbaileynar have you seen this before?

**Comment by nanaesri** [comment]
Sure.. I hope it keeps that way... all is ok
I am trying to master it now.
Thanks for your support and time.
