### ISSUE TITLE
Can't install GCD 7.1.1

### ISSUE THREAD

**Issue by kbartelt** [Riverscapes/gcd#294]
## The Problem

When trying to install stand alone GCD 7.1.10, it fails on install... 
What went wrong?

## Reproduction steps

1. Ran `2018_06_29_GCDStandAlone_7_1_1.exe`
2. Accepted security warning
3. Saw message below

## Exception message

```
Cannot download the application. The application is missing required files. Contact application vendor for assistance.
```

It provides these details:

```PLATFORM VERSION INFO
	Windows 			: 10.0.17134.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.3056.0 built by: NET472REL1
	clr.dll 			: 4.7.3110.0 built by: NET472REL1LAST_C
	dfdll.dll 			: 4.7.3056.0 built by: NET472REL1
	dfshim.dll 			: 10.0.17134.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/A02295870/Documents/GCDStandalone.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\A02295870\Documents\GCDStandalone.application resulted in exception. Following failure messages were detected:
		+ Downloading file:///C:/Users/A02295870/Documents/GCDStandalone.application did not succeed.
		+ Could not find file 'C:\Users\A02295870\Documents\GCDStandalone.application'.
		+ Could not find file 'C:\Users\A02295870\Documents\GCDStandalone.application'.
		+ Could not find file 'C:\Users\A02295870\Documents\GCDStandalone.application'.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [7/2/2018 1:21:19 PM] : Activation of C:\Users\A02295870\Documents\GCDStandalone.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [7/2/2018 1:21:19 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading file:///C:/Users/A02295870/Documents/GCDStandalone.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'C:\Users\A02295870\Documents\GCDStandalone.application'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'C:\Users\A02295870\Documents\GCDStandalone.application'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			at System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- Inner Exception ---
		System.IO.FileNotFoundException
		- Could not find file 'C:\Users\A02295870\Documents\GCDStandalone.application'.
		- Source: mscorlib
		- Stack trace:
			at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.


```

**Comment by philipbaileynar** [comment]
Thanks for reporting this issue @kbartelt. We have fixed and tested the new release of 7.1.1. Please try again and let us know if it doesn't work for you. If it works, please **close this issue**.

https://github.com/Riverscapes/gcd/releases/tag/7.1.1

**Comment by joewheaton** [comment]
@philipbaileynar, are you saying that since yesterday, the new release of 7.1.1 has been updated? It doesn't look like it (we tried this yesterday on both @kbartelt and @mllenah machines and had same problem on both. Interestingly, I tried the same thing just now and had no problems:

https://youtu.be/WavVTfCZWE4

**Comment by philipbaileynar** [comment]
Yes @joewheaton a new release of 7.1.1 was release this morning (PST). Same version number but with today's date.

**Comment by kbartelt** [comment]
@philipbaileynar @joewheaton I just tried this again and was able to install the stand alone 7.1.1 with no issues. Thanks!
