### ISSUE TITLE
3D Point Quality Surface Problem

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#296]
Old email:

> Dear Joseph
> 
> I’m a student at, Vrije Universiteit Brussel and I’m currently writing my Master dissertation on Monitoring sediment volume changes of natural and urbanized macro-tidal sandy beaches along the Belgian coastline. I’m running a bit into trouble when producing a 3D point quality surface and a point density surface. What should I do to solve this problem?
> 
> 
> Object reference not set to an instance of an object.
> 
```
--- Stacktrace ---

    at GCDAddIn.GISCode.GISDataStructures.Raster.get_RasterStatistics() in D:\Code\gcd\gcd-addin\GISCode\GISDataStructures\Raster.vb:line 223
 
    at GCDAddIn.GISCode.GCD.GCDArcMapManager.AddAssociatedSurface(AssociatedSurfaceRow assocRow) in D:\Code\gcd\gcd-addin\GISCode\GCD\ArcMapGCD.vb:line 216
 
    at GCDAddIn.SurfacePropertiesForm.btnOK_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd-addin\SurveyLibrary\SurfacePropertiesForm.vb:line 180Windows: 6.2.9200.0
 
 Date: 3/30/2018 12:08:10 PM
 
  
 
 Tool: Geomorphic Change Detection version 6.1.14.0
 
 ArcMap: 10.3.0.4284
 
  
 
 Object reference not set to an instance of an object.
 
 --- Stacktrace ---
 
    at ESRI.ArcGIS.Carto.RasterLayerClass.CreateFromDataset(IRasterDataset RasterDataset)
 
    at GCDAddIn.GISCode.GCD.GCDArcMapManager.AddRasterLayer(IMxDocument pMXDoc, Raster gRaster, IRasterRenderer rasterRenderer, String sRasterName, IGroupLayer pGrpLyr, String sHeader, Double fTransparency) in D:\Code\gcd\gcd-addin\GISCode\GCD\ArcMapGCD.vb:line 832
 
    at GCDAddIn.GISCode.GCD.GCDArcMapManager.AddAssociatedSurface(AssociatedSurfaceRow assocRow) in D:\Code\gcd\gcd-addin\GISCode\GCD\ArcMapGCD.vb:line 208
 
    at GCDAddIn.SurfacePropertiesForm.btnOK_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd-addin\SurveyLibrary\SurfacePropertiesForm.vb:line 180Windows: 6.2.9200.0
 
 Date: 3/30/2018 12:17:00 PM
 
  
 
 Tool: Geomorphic Change Detection version 6.1.14.0
 
 ArcMap: 10.3.0.4284
> 
>  
> 
> Kind Regards,

**Comment by joewheaton** [comment]
Amanda, I'm so sorry for having missed this message. We've now replaced GCD 6 with [GCD 7](http://gcd.riverscapes.xyz) and are no longer supporting 6. So, the first troubleshooting step will be try to reproduce problem in GCD 7. I do see you are on 10.3? Unfortunately, you'll either have to upgrade tod ArcGIS 10.4 or later or use the GCD 7 standalone. Please let us know if the problem persists.

**Comment by philipbaileynar** [comment]
Closing inactive issue.
