### ISSUE TITLE
Clean Raster dialog throws an error

### ISSUE THREAD

**Issue by Hornbydd** [Riverscapes/gcd#301]
## The Problem

I was following the tutorial on this [web page](http://gcd.riverscapes.xyz/Help/Tutorials/BuildingDEMs/bestpractices.html) Exercise F part 3. and I am unable to progress.

## Reproduction steps

1. Clicked on Data Preparation > Clean Raster (note it only has 1 option whilst video shows several other menu options)
2. There is no drop down, it does not appear to be picking up on the fact the raster is in the TOC.
3. Click Add data button under original Raster, error dialog pops up...

## Exception message

Object reference not set to an instance of an object.
 --- Stacktrace --- 
   at GCDAddIn.DataPreparation.btnCleanRaster.BrowseRaster(Object sender, PathEventArgs e) in D:\Code\gcd\gcd\GCDAddIn\DataPreparation\btnCleanRaster.cs:line 38
   at GCDCore.UserInterface.UtilityForms.ucRasterInput.BrowseRasterEventHandler.Invoke(TextBox txtPath, PathEventArgs e)
   at GCDCore.UserInterface.UtilityForms.ucRasterInput.cmdBrowseRaster_Click(Object sender, PathEventArgs e)
 --- Exception Data --- 
ArcMap = 10.6.0.8321
GCD = 7.1.1.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 09/08/2018 18:00:51

Please watch animated gif to see sequence. I'm working on a project with Joe so if this is a step I must do this needs to be fixed asap, thanks.

![error_gcd7](https://user-images.githubusercontent.com/22773948/43914258-4d45f8e4-9bff-11e8-90cb-12aa3c456fdb.gif)

**Comment by philipbaileynar** [comment]
Thanks for filing this issue @hornbydd. I will investigate after 17th August. 

Nice animated GIF BTW

**Comment by joewheaton** [comment]
@Hornbydd in the meantime, the same functionality of the Clean Raster tool is in loading in with Add Survey to Project.

**Comment by philipbaileynar** [comment]
We can fix it or deprecate it, but it can't go in TAT for technical reasons.

**Comment by philipbaileynar** [comment]
I just reproduced this error using the Pats Cabin data obtained from the tutorial page link in the original issue post above:

```
Object reference not set to an instance of an object.
 --- Stacktrace --- 
   at GCDAddIn.DataPreparation.btnCleanRaster.BrowseRaster(Object sender, PathEventArgs e) in D:\Code\gcd\gcd\GCDAddIn\DataPreparation\btnCleanRaster.cs:line 38
   at GCDCore.UserInterface.UtilityForms.ucRasterInput.BrowseRasterEventHandler.Invoke(TextBox txtPath, PathEventArgs e)
   at GCDCore.UserInterface.UtilityForms.ucRasterInput.cmdBrowseRaster_Click(Object sender, PathEventArgs e) in D:\Code\gcd\gcd\GCDCore\UserInterface\UtilityForms\ucRasterInput.cs:line 46
 --- Exception Data --- 
ArcMap = 10.4.1.5686
GCD = 7.1.1.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 8/22/2018 11:00:12 AM
```
