### ISSUE TITLE
Improved GCD Unit Exception Handling

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#317]
We have had approx half a dozen users contact us because their rasters have unknown unit types. The error message looks like the code block at the bottom of this issue.

Notice how the `Unit =` is followed by an empty string and then immediately by the Windows version number. We need to improve this exception message so that we can deduce what projections and units are causing the problem. Without this information we have to ask the user to zip and send their rasters which is extremely inefficient and often results in no response.

Probably the best way to handling this is to try/catch the `GetLinearUnitsFromString()` exception and include the entire SRS well known string in the exception message. This will enable us to create our own rasters with the same projection information, ultimately reproducing the same error.

```
Unhandled linear unit type.
 --- Stacktrace --- 
   at GCDAddIn.GISCode.NumberFormatting.GetLinearUnitsFromString(String sLinearUnits) in D:\Code\gcd\gcd-addin\GISCode\General\NumberFormatting.vb:line 915
   at GCDAddIn.GISCode.GCD.ChangeDetection.ChangeDetectionEngineMinLOD.Calculate(String& sRawDoDPath, String& sThreshDodPath, String& sRawHistPath, String& sThreshHistPath, String& sSummaryXMLPath) in D:\Code\gcd\gcd-addin\GISCode\GCD\ChangeDetection\ChangeDetectionEngineMinLOD.vb:line 50
   at GCDAddIn.DoDPropertiesForm.cmdOK_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd-addin\ChangeDetection\DoD\DoDPropertiesForm.vb:line 172
 --- Exception Data --- 
 Unit = Windows: 6.2.9200.0
Date: 04.09.2018 20:14:26

Tool: Geomorphic Change Detection version 6.1.14.0
ArcMap: 10.6.0.8321

```

**Comment by emma994** [comment]
Hi Philip,
I have been getting this error message when trying to compare two rasters. I also tested it with the 'River Dee, Scotland' data available on your website. Do you know if there is any way around this or when the bug/enhancement is likely to be resolved?
Thanks, Emma

**Comment by philipbaileynar** [comment]
Hi @emma994,

I just performed the following steps without error:

1. Downloaded a fresh copy of the [Dee dataset from the web site](http://gcd.riverscapes.xyz/Help/example-data-sets.html).
1. Created a new GCD project using version 7.3.0.
1. Imported both the 2011 and 2016 DEM rasters from the download.
1. Performed a DoD.

![2018-10-09_100018](https://user-images.githubusercontent.com/8645379/46685544-96390c00-cbaa-11e8-942c-5ba9a3a3eb28.png)

I want to help overcome your issue, but I need more information from you:

1. What version of the GCD are you running?
1. Are you running GCD Within ArcMap or are you running the GCD standalone?
1. If you're running GCD within ArcMap what version of ArcGIS are you running?
1. Can you provide some screenshots of the error? Try and configure your windows so that I can see both the GCD project tree, any windows you are using to perform a GCD operation as well as the error. In other words, cascade the windows like I have in the screenshot above.
1. Best of all would be a video of you running GCD from the point of creating a new project to producing the error. I recommend the excellent, inexpensive [FastStone Capture tool](http://www.faststone.org/FSCaptureDetail.htm).
