### ISSUE TITLE
Errors in GCD 6.1.14 from user

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/gcd#327]
## The Problem
Sent from a user via email:
> Good Morning,
> 
> 
> I have been using GCD 6 to analyse a small pilot study set of data and I was hoping that you might be able to help.
> 
> 
> I used the 'Create TIN and/or DEM' option in the data preparation menu to generate a dem from my point data, however when I then try to use the clean tool on that dataset it will not load.
> 
> 
> When I try to add the dem to the 'original raster' field it just freezes up. I have since managed to make it work without any issues by using the Arc 'tin to raster' tool instead (using the intermediate tin generated from the create tin and/or dem' tool) so I was wondering if this was something you already knew about and could suggest what I may have done wrong t cause this issue?
> 
> 
> Thank you.
> 
> Best wishes
> 
> Becky

## Reproduction steps

> I  have been getting the following error message when trying to compare two raster datasets in GCD

## Exception message

```text

--- Stacktrace --- 
   at GCDAddIn.GISCode.NumberFormatting.GetLinearUnitsFromString(String sLinearUnits) in D:\Code\gcd\gcd-addin\GISCode\General\NumberFormatting.vb:line 915
   at GCDAddIn.GISCode.GCD.ChangeDetection.ChangeDetectionEngineMinLOD.Calculate(String& sRawDoDPath, String& sThreshDodPath, String& sRawHistPath, String& sThreshHistPath, String& sSummaryXMLPath) in D:\Code\gcd\gcd-addin\GISCode\GCD\ChangeDetection\ChangeDetectionEngineMinLOD.vb:line 50
   at GCDAddIn.DoDPropertiesForm.cmdOK_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd-addin\ChangeDetection\DoD\DoDPropertiesForm.vb:line 172
 --- Exception Data --- 
 Unit = Windows: 6.2.9200.0
Date: 06/11/2018 13:01:37

Tool: Geomorphic Change Detection version 6.1.14.0
ArcMap: 10.5.1.7333
```

## Anything else?

> I have performed the GCD analysis on this data using an older version of the software, but it doesn't seem to work now.
> 
> 
> I've tried it a few times using a few different criteria but it just doesn't seem to want to work.
> 
> 
> Any advice would be appreciated.
>

**Comment by joewheaton** [comment]
Hi Becky, 
We are [no longer supporting GCD 6 or earlier](http://gcd.riverscapes.xyz/Download/old_versions.html). It has been replaced by [GCD 7](http://gcd.riverscapes.xyz). I strongly suspect the specific error you are getting will not occur in GCD 7, given the refactoring and improvements to unit and projection handling. Please let us know if that is not the case. 

Also, with regards to:

> I  used the 'Create TIN and/or DEM' option in the data preparation menu to generate a dem from my point data, however when I then try to use the clean tool on that dataset it will not load.

That was included in an old version of GCD, but we never actually were building our own TINs or DEMs (we were just using ESRI's flaky geoprocessing to do it). As such, it is very hard to support their tools and we've removed that. Just do what you did (i.e. build your TIN or DEM outside GCD), but do have a  look at: 
- http://gcd.riverscapes.xyz/Help/Tutorials/BuildingDEMs/building-dems.html
- http://gcd.riverscapes.xyz/Help/Tutorials/BuildingDEMs/bestpractices.html

If you still have trouble, please post a new post to [issue forum](http://gcd.riverscapes.xyz/Help/#issue-forum).

**Comment by joewheaton** [comment]
From user:

> To whom it may concern,
> 
> I faced this problem while trying to detect the changes in my GCD project. 
> Do you know what the problem can be?
> 
> "Unhandled linear unit type.
>  --- Stacktrace --- 
>    at GCDAddIn.GISCode.NumberFormatting.GetLinearUnitsFromString(String sLinearUnits) in D:\Code\gcd\gcd-addin\GISCode\General\NumberFormatting.vb:line 915
>    at GCDAddIn.GISCode.GCD.ChangeDetection.ChangeDetectionEngineMinLOD.Calculate(String& sRawDoDPath, String& sThreshDodPath, String& sRawHistPath, String& sThreshHistPath, String& sSummaryXMLPath) in D:\Code\gcd\gcd-addin\GISCode\GCD\ChangeDetection\ChangeDetectionEngineMinLOD.vb:line 50
>    at GCDAddIn.DoDPropertiesForm.cmdOK_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd-addin\ChangeDetection\DoD\DoDPropertiesForm.vb:line 172
>  --- Exception Data --- 
>  Unit = Windows: 6.2.9200.0
> Date: 06/11/2018 18:05:34
> 
> Tool: Geomorphic Change Detection version 6.1.14.0
> ArcMap: 10.3.1.4959"
> 
> Your sincerely,
> 
> Giacomo Pellegrini

Please see links above. Same error... same answer. Upgrade to GCD 7 where this should have been fixed.
