### ISSUE TITLE
"Error editing single region error surface"

### ISSUE THREAD

**Issue by mllenah** [Riverscapes/gcd#337]
## The Problem

When I try to create an FIS error model from two associated surfaces (i.e. Slope and roughness) this message appears and the model is not created.

## Reproduction steps

I have done this process several times and I have never had this problem. The only difference this time is that the DEM from which the associated surfaces were created was orthogonal and divisible with the specified output so any interpolation was required.

## Exception message

```Both rasters must have the same vertical units: `Meter` vs. `Undefined`
 --- Stacktrace --- 
   at GCDConsoleLib.Raster.ValidateSameMeta(Raster rR1, Raster rR2, Boolean ignoreProj) in D:\Code\gcd\gcd\GCDConsoleLib\Raster.cs:line 372
   at GCDConsoleLib.Internal.BaseOperator`1.AddInputRaster(Raster rInput) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 131
   at GCDConsoleLib.Internal.Operators.CreateErrorRaster..ctor(Raster rawDEM, ErrorRasterProperties prop, Raster rOutputRaster) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\CreateErrorRaster.cs:line 50
   at GCDConsoleLib.RasterOperators.CreateErrorRaster(Raster rawDEM, ErrorRasterProperties props, FileInfo sOutputRaster, EventHandler`1 progressHandler) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 787
   at GCDCore.UserInterface.SurveyLibrary.ErrorSurfaces.frmSingleMethodError.cmdOK_Click(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.5.0.6491
GCD = 7.2.0.0
Windows: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 22/01/2019 7:49:58

```

## Anything else?

You can attach links to datasets.

**Comment by mllenah** [comment]
Hi again,

Seems that the problem was related with the spatial reference. Input files (i.e. DEM and associated surfaces) were in the same XY Coordinate System but the Vertical Coordinate System was different. I've corrected this and the problem was solved.

Thank you anyway!
