### ISSUE TITLE
Raster Subraction Exception

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#340]
Reported by @emma994 on 30 Jan 2019 as a follow up to resolving issue #338.

Thanks for your advice, that has worked and I can now load the two raster files into my GCD project. However, when I am conducting a change detection I am now getting the following error message:

```
EXCEPTION
Exception has been thrown by the target of an invocation.
 --- Stacktrace --- 
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at GCDConsoleLib.RasterOperators.GenericRunWithOutput(Type generic, Type innerType, String sDesc, EventHandler`1 progressHandler, Object[] args) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 1293
   at GCDConsoleLib.RasterOperators.Subtract(Raster rInputA, Raster rInputB, FileInfo sOutputRaster, EventHandler`1 progressHandler) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 159
   at GCDCore.Engines.ChangeDetectionEngineBase.Calculate(String dodName, DirectoryInfo analysisFolder, Boolean bBuildPyramids, UnitGroup units)
   at GCDCore.UserInterface.ChangeDetection.frmDoDProperties.cmdOK_Click(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.5.1.7333
GCD = 7.4.0.0Index was outside the bounds of the array.
 --- Stacktrace --- 
   at GCDConsoleLib.Common.Extensons.ArrayExtensions.Plunk[T](T[] dstData, T[] srcData, Int32 dstSizeR0, Int32 dstSizeR1, Int32 srcSizeR0, Int32 srcSizeR1, Int32 offsetR0, Int32 offsetR1) in D:\Code\gcd\gcd\GCDConsoleLib\Extensions\ArrayExtensions.cs:line 121
   at GCDConsoleLib.Internal.BaseOperator`1.GetChunk(List`1 data) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 334
   at GCDConsoleLib.Internal.BaseOperator`1.Run() in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 411
   at GCDConsoleLib.Internal.BaseOperator`1.RunWithOutput() in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 448
Windows: Microsoft Windows NT 6.2.9200.0
Date: 30/01/2019 10:24:50
```

**Comment by emma994** [comment]
Hi @philipbaileynar,
I was wondering if you knew what this error message means?

**Comment by philipbaileynar** [comment]
@emma994 we have not seen this issue before. Could you please zip your GCD project and send it to us? It will probably be too big for email. Do you have another means of transmitting it?

**Comment by emma994** [comment]
@philipbaileynar I could send it over onedrive if you have access to this. Do you have an email address for me to share it with?

**Comment by philipbaileynar** [comment]
info@northarrowresearch.com

**Comment by emma994** [comment]
Hi @philipbaileynar 
I've tried sending a link of my data over to that email address via one drive but I keep getting an email bounce back saying message unable to deliver

**Comment by philipbaileynar** [comment]
Try philip@northarrowresearch.com

**Comment by philipbaileynar** [comment]
Just to confirm @ that I have the data.

**Comment by philipbaileynar** [comment]
@emma994 this error is actually a red herring. The raster subtraction is failing because your rasters have different cell resolutions. While you should have handled this in your data prep, GCD should not let you add both rasters to your GCD project without first fixing this problem. I have logged this issue (#341) and will tackle it ASAP. In the meantime see the bottom of this issue for a quick worksaround.

The two cell resolutions in these screenshots from your GCD project must be the same: 

![2019_02_07_145103](https://user-images.githubusercontent.com/8645379/52448207-04092c00-2ae8-11e9-8146-4b9c08983a93.png)

## Temporary Workaround

1. Create a new blank GCD project.
1. Click to add a new DEM survey and browse to your first raster (doesn't matter which, but I chose the 2017 raster).
1. In the raster properties form that appears change the precision to 2 and the cell resolution to 0.07. ![2019_02_07_145642](https://user-images.githubusercontent.com/8645379/52448416-ade8b880-2ae8-11e9-88be-711aa2389900.png)
1. Click Add raster and wait for it to process.
1. Now add the second DEM survey and ensure that the cell resolution and precision controls at the bottom of the form show the **identical** values as you specified above. (Note that the controls will be read only the second time that you use the form).

**Comment by philipbaileynar** [comment]
Closing this issue because it is the result of rasters within the same project having different cell resolutions which should never occur. Issue #341 is now resolved and so this situation should never occur again.
