### ISSUE TITLE
Installation Issue - GCDStadalone version 7.4.0

### ISSUE THREAD

**Issue by spgriffin** [Riverscapes/gcd#342]
## The Problem

An error occurred trying to download 'http://releases.northarrowresearch.com/GCD/StandAlone/GCDStandalone.application'.

## Exception message

PLATFORM VERSION INFO
	Windows 			: 10.0.17134.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.3056.0 built by: NET472REL1
	clr.dll 			: 4.7.3260.0 built by: NET472REL1LAST_C
	dfdll.dll 			: 4.7.3056.0 built by: NET472REL1
	dfshim.dll 			: 10.0.17134.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/RDGRL/Downloads/GCDStandalone.application

IDENTITIES
	Deployment Identity		: GCDStandalone.application, Version=1.0.0.30, Culture=neutral, PublicKeyToken=5c9dbb5da717ecd1, processorArchitecture=amd64

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\RDGRL\Downloads\GCDStandalone.application resulted in exception. Following failure messages were detected:
		+ Deployment and application do not have matching security zones.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [2/7/2019 8:52:47 PM] : Activation of C:\Users\RDGRL\Downloads\GCDStandalone.application has started.
	* [2/7/2019 8:52:47 PM] : Processing of deployment manifest has successfully completed.
	* [2/7/2019 8:52:47 PM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2/7/2019 8:52:47 PM] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Deployment and application do not have matching security zones.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by philipbaileynar** [comment]
Closing inactive issue.
