### ISSUE TITLE
Error browsing to mask vector file

### ISSUE THREAD

**Issue by wwicherski** [Riverscapes/gcd#347]
## The Problem

Cannot upload mask file to the 

## Reproduction steps

1. I created a singlepart polygon to use as an area of interest mask to distinguish the water surface from the ground surface.
2. I tried to upload the polygon using the mask tool but get an error about browsing to the vector file.

## Exception message

```text

------------------------------------------------
EXCEPTION
Error attempting to browse for vector GIS data source
 --- Stacktrace --- 
   at GCDAddIn.ArcMapBrowse.BrowseOpenVector(String formTitle, DirectoryInfo diWorkspace, String sFCName, BrowseGISTypes eType, IntPtr hParentWindowHandle) in D:\Code\gcd\gcd\GCDAddIn\ArcMapBrowse.cs:line 107
   at GCDAddIn.ucProjectManager.AddinImpl.OnGISBrowseVector(TextBox txt, PathEventArgs e, SimpleTypes geometryType) in D:\Code\gcd\gcd\GCDAddIn\ucProjectManager.cs:line 103
   at GCDCore.Project.ProjectManager.OnBrowseVector(TextBox txt, PathEventArgs e, SimpleTypes geometryType)
   at GCDCore.UserInterface.UtilityForms.ucVectorInput.cmdBrowse_Click(Object sender, PathEventArgs e)
 --- Exception Data --- 
ArcMap = 10.6.1.9270
GCD = 7.3.0.0Can't load requested DLL: C:\Python27\Lib\site-packages\osgeo\gdalplugins\ogr_PG.dll
126: The specified module could not be found.

 --- Stacktrace --- 
   at OSGeo.OGR.Ogr.RegisterAll()
   at GCDConsoleLib.GdalConfiguration.ConfigureOgr() in D:\Code\gcd\gcd\GCDConsoleLib\Utility\GdalConfiguration.cs:line 106
   at GCDConsoleLib.Vector.Open(Boolean write) in D:\Code\gcd\gcd\GCDConsoleLib\Vector.cs:line 143
   at GCDConsoleLib.Vector._load(Boolean leaveopen) in D:\Code\gcd\gcd\GCDConsoleLib\Vector.cs:line 410
   at GCDConsoleLib.Vector..ctor(FileInfo sFilename) in D:\Code\gcd\gcd\GCDConsoleLib\Vector.cs:line 36
   at GCDAddIn.ArcMapBrowse.BrowseOpenVector(String formTitle, DirectoryInfo diWorkspace, String sFCName, BrowseGISTypes eType, IntPtr hParentWindowHandle) in D:\Code\gcd\gcd\GCDAddIn\ArcMapBrowse.cs:line 102
Windows: Microsoft Windows NT 6.2.9200.0
Date: 2/26/2019 9:07:01 AM

```

**Comment by philipbaileynar** [comment]
@wwicherski :

1. Note that there is a newer version of GCD available.
1. What is the the storage type of your polygon layer? Is it a ShapeFile, geodatabase etc?
1. What map projection does your layer use?

**Comment by wwicherski** [comment]
1: I will try and download the new version and see if that helps.  
2: The polygon is stored as a shapefile.  
3: My polygon uses WGS84 UTM Zone 10N.

**Comment by philipbaileynar** [comment]
Closing old issue due to lack of communication.
