### ISSUE TITLE
Error Importing DEM Survey

### ISSUE THREAD

**Issue by simonhird1** [Riverscapes/gcd#348]
## The Problem

Hello, I'm using the GCD 7 software to look at coastal geomorphic change for a masters coursework. But I am having difficulty uploading my DEMs into GCD 7. As soon as I go to add an existing DEM survey I receive this error. I may be doing something blindingly wrong so I apologise in advance.

## Exception message
Object reference not set to an instance of an object.
 --- Stacktrace --- 
   at GCDCore.UserInterface.SurveyLibrary.GISDatasetValidation.DSHasSpatialRef(GISDataset gisDS, String sTypeSingle, String sTypePlural)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.PrepareToImportRaster(Surface refSurface, Purposes purpose, String Noun, IntPtr parentWindow)
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.6.0.8321
GCD = 7.4.1.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 01/05/2019 13:39:23

**Comment by simonhird1** [comment]
Solved! Hadn't saved the file as a tif...

**Comment by cpforester** [comment]
Hi Simon, 

Can you please outline the steps you took to resolve the issue? I am having the same problem. Thanks.

**Comment by philipbaileynar** [comment]
@cpforester what file format is your raster? 

If it is not a GeoTiff then load the raster into ArcGIS Desktop and then right click and "export" being sure to choose the GeoTiff raster file format.

**Comment by cpforester** [comment]
Hi @philipbaileynar,

I was able to export the layer to TIFF format but not GeoTiff, as this was not an option to me. Does it matter if the extent or spatial reference is the original raster or data frame? This is the new error I received after trying to import the TIFF file. 

EPSG PCS/GCS code 6360 not found in EPSG support files.  Is this a valid EPSG coordinate system?
 --- Stacktrace --- 
   at OSGeo.GDAL.Band.GetUnitType()
   at GCDConsoleLib.Raster._initfromfile() in D:\Code\gcd\gcd\GCDConsoleLib\Raster.cs:line 186
   at GCDConsoleLib.GISDataset.get_Proj() in D:\Code\gcd\gcd\GCDConsoleLib\GISDataset.cs:line 19
   at GCDCore.UserInterface.SurveyLibrary.GISDatasetValidation.DSHasSpatialRef(GISDataset gisDS, String sTypeSingle, String sTypePlural)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.PrepareToImportRaster(Surface refSurface, Purposes purpose, String Noun, IntPtr parentWindow)
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.7.0.10450
GCD = 7.4.3.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 10/1/2019 1:59:31 PM

**Comment by philipbaileynar** [comment]
What map projection are you using? Have you tried a common UTM or state plane projection?

**Comment by cpforester** [comment]
I am using a state plane projection. I was able to import a previous TIFF file I found, but it seems the extent is non-divisible. I was hoping to use the files I created to mitigate the issue. I will have to look more into prepping my data, I suppose. Thanks for your feedback!
