### ISSUE TITLE
Cannot add DEMs with EPSG code 5703

### ISSUE THREAD

**Issue by jcaseyroot** [Riverscapes/gcd#349]
## The Problem

Cannot add DEMs with EPSG code 5703

## Reproduction steps

1. "Add existing DEM survey" - DEM in question has horizontal coordinate system NAD_1983_2011_UTM_Zone_12N and vertical NAVD_1988.

## Exception message

EPSG PCS/GCS code 5703 not found in EPSG support files.  Is this a valid EPSG coordinate system?
 --- Stacktrace --- 
   at OSGeo.GDAL.Band.GetUnitType()
   at GCDConsoleLib.Raster._initfromfile() in D:\Code\gcd\gcd\GCDConsoleLib\Raster.cs:line 186
   at GCDConsoleLib.GISDataset.get_Proj() in D:\Code\gcd\gcd\GCDConsoleLib\GISDataset.cs:line 19
   at GCDCore.UserInterface.SurveyLibrary.GISDatasetValidation.DSHasSpatialRef(GISDataset gisDS, String sTypeSingle, String sTypePlural)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.PrepareToImportRaster(Surface refSurface, Purposes purpose, String Noun, IntPtr parentWindow)
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.6.1.9270
GCD = 7.4.1.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 5/20/2019 4:05:46 PM

```

## Anything else?

You can attach links to datasets.

**Comment by philipbaileynar** [comment]
Hi @jcaseyroot how big is your raster? Are you able to zip it up and get it to me somehow please?

What file format is your raster in? GeoTIF or IMG file?

**Comment by jcaseyroot** [comment]
It's a 900mb GeoTIF that is currently in review so I can't share it publicly quite yet - could I send it to a private email perhaps?

**Comment by philipbaileynar** [comment]
@jcaseyroot please zip and make available to philip@northarrowresearch.com. Even zipped it will probably be too big for email, but perhaps you can use a cloud service etc.

**Comment by philipbaileynar** [comment]
Closing inactive issue.
