### ISSUE TITLE
"Error editing single region error surface"

### ISSUE THREAD

**Issue by Jo-Bind** [Riverscapes/gcd#360]
## The Problem
When trying to create a FIS error model with slope and point density, the error message "Error editing single region error surface" pops up.

## Reproduction steps

1. I calculated point density and slope rasters as associated surfaces to the surveyed DEMs
2. All rasters are concurrent and orthogonal and have the same coordinate system specified.
3. When trying to calculate a new FIS error model, the above message appears.

## Exception message

```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
 --- Stacktrace --- 
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at GCDConsoleLib.FIS.RuleSet.calculate(List`1 dataArrays, Int32 n, Boolean checkNoData, List`1 noDataValues, Double noData) in D:\Code\gcd\gcd\GCDConsoleLib\FIS\RuleSet.cs:line 245
   at GCDConsoleLib.Internal.Operators.CreateErrorRaster.CellChangeCalc(String propkey, List`1 data, Int32 id) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\CreateErrorRaster.cs:line 150
   at GCDConsoleLib.Internal.Operators.CreateErrorRaster.CellOp(List`1 data, List`1 outputs, Int32 id) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\CreateErrorRaster.cs:line 199
   at GCDConsoleLib.Internal.CellByCellOperator`1.ChunkOp(List`1 data, List`1 outChunks) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\CellByCellOperator.cs:line 90
   at GCDConsoleLib.Internal.BaseOperator`1.Run() in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 417
   at GCDConsoleLib.RasterOperators.CreateErrorRaster(Raster rawDEM, ErrorRasterProperties props, FileInfo sOutputRaster, EventHandler`1 progressHandler) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 792
   at GCDCore.UserInterface.SurveyLibrary.ErrorSurfaces.frmSingleMethodError.cmdOK_Click(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.6.0.8321
GCD = 7.4.1.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 24/09/2019 12:59:19 PM
```

## Anything else?

You can attach links to datasets.
![image](https://user-images.githubusercontent.com/55743678/65506693-73435d00-decc-11e9-9363-245e0fb0d310.png)

**Comment by TMNGuy** [comment]
I am also having the same error, which I don't understand. I just added a new DEM to a previous project that was able to create previous FIS surfaces but now I keep getting this error when I try to make an new FIS? 

the parameters are still the same, my method for processing has not changed. The input are in meters, I am not sure what is undefined. 


**Error editing single region error surface**
Both rasters must have the same vertical units: `Meter` vs. `Undefined`
 --- Stacktrace --- 
   at GCDConsoleLib.Raster.ValidateSameMeta(Raster rR1, Raster rR2, Boolean ignoreProj)
   at GCDConsoleLib.Internal.BaseOperator`1.AddInputRaster(Raster rInput)
   at GCDConsoleLib.Internal.Operators.CreateErrorRaster..ctor(Raster rawDEM, ErrorRasterProperties prop, Raster rOutputRaster)
   at GCDConsoleLib.RasterOperators.CreateErrorRaster(Raster rawDEM, ErrorRasterProperties props, FileInfo sOutputRaster, EventHandler`1 progressHandler)
   at GCDCore.UserInterface.SurveyLibrary.ErrorSurfaces.frmSingleMethodError.cmdOK_Click(Object sender, EventArgs e)
 --- Exception Data --- 
GCD = 7.4.4.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 12/30/2020 12:49:09 PM
