### ISSUE TITLE
Error browsing to vector mask

### ISSUE THREAD

**Issue by wangbo6418** [Riverscapes/gcd#364]
## The Problem

What went wrong?

## Reproduction steps

1. I tried to add regular mask in GCD7. The projection of the shp file is "NAD_1983_StatePlane_Louisiana_South_FIPS_1702_Feet" 

However, it shows the wrong information below. I have no idea how to deal with it. Please help.

------------------------------------------------
EXCEPTION
Error attempting to browse for vector GIS data source
 --- Stacktrace --- 
   at GCDAddIn.ArcMapBrowse.BrowseOpenVector(String formTitle, DirectoryInfo diWorkspace, String sFCName, BrowseGISTypes eType, IntPtr hParentWindowHandle) in D:\Code\gcd\gcd\GCDAddIn\ArcMapBrowse.cs:line 107
   at GCDAddIn.ucProjectManager.AddinImpl.OnGISBrowseVector(TextBox txt, PathEventArgs e, SimpleTypes geometryType) in D:\Code\gcd\gcd\GCDAddIn\ucProjectManager.cs:line 103
   at GCDCore.Project.ProjectManager.OnBrowseVector(TextBox txt, PathEventArgs e, SimpleTypes geometryType)
   at GCDCore.UserInterface.UtilityForms.ucVectorInput.cmdBrowse_Click(Object sender, PathEventArgs e)
 --- Exception Data --- 
ArcMap = 10.5.0.6491
GCD = 7.3.0.0Could not parse unit string: Foot_US
 --- Stacktrace --- 
   at GCDConsoleLib.Utility.Conversion.ParseLengthUnit(String u) in D:\Code\gcd\gcd\GCDConsoleLib\Utility\Conversion.cs:line 322
   at GCDConsoleLib.Projection._Init() in D:\Code\gcd\gcd\GCDConsoleLib\Projection.cs:line 55
   at GCDConsoleLib.Projection..ctor(String sWkt) in D:\Code\gcd\gcd\GCDConsoleLib\Projection.cs:line 27
   at GCDConsoleLib.Vector._load(Boolean leaveopen) in D:\Code\gcd\gcd\GCDConsoleLib\Vector.cs:line 447
   at GCDConsoleLib.Vector..ctor(FileInfo sFilename) in D:\Code\gcd\gcd\GCDConsoleLib\Vector.cs:line 36
   at GCDAddIn.ArcMapBrowse.BrowseOpenVector(String formTitle, DirectoryInfo diWorkspace, String sFCName, BrowseGISTypes eType, IntPtr hParentWindowHandle) in D:\Code\gcd\gcd\GCDAddIn\ArcMapBrowse.cs:line 102
Windows: Microsoft Windows NT 6.1.7601 Service Pack 1
Date: 10/6/2019 2:05:13 PM
## Anything else?

You can attach links to datasets.

**Comment by philipbaileynar** [comment]
Please uninstall GCD and update to the latest version 7.4.3.

The problem is cause by your data using US survey feet instead of international feet. I believe that latest version can handle both.

**Comment by wangbo6418** [comment]
Thank you very much. It works after I install  7.4.3.
