### ISSUE TITLE
Error importing DEM surveys

### ISSUE THREAD

**Issue by Jboy036** [Riverscapes/gcd#374]
##Error importing DEM surveys

Error importing DEM surveys

## Reproduction steps

Tried importing DEM surveys into GCD Inputs, but get the below error message. 

Object reference not set to an instance of an object.
 --- Stacktrace --- 
   at GCDCore.UserInterface.SurveyLibrary.GISDatasetValidation.DSHasSpatialRef(GISDataset gisDS, String sTypeSingle, String sTypePlural)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.PrepareToImportRaster(Surface refSurface, Purposes purpose, String Noun, IntPtr parentWindow)
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.6.0.8321
GCD = 7.4.2.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 16/12/2019 2:22:24 PM

**Comment by Jboy036** [comment]
All fixed, I just needed to export the raster DEM as a TIFF into a folder.
