### ISSUE TITLE
GCD FIS failing

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#38]
Michael Grilliot of UVic has forwarded his GCD 7 project that is throwing the following FIS error. He is using a custom FIS rule file and I suspect that he has something invalid in this file.

Note that he actually had two issues. The first being that associated surfaces were not being copied into the project correctly. I have logged this separately, but worked around this by copying his roughness associated raster into the project by hand. I don't think this is related.

His GCD project is available within NAR in a file called `WBGCDv7_fixedassoc.zip`. I've copied his FIS file to the root of this zip file.

When debugging this issue you should only attempt to generate an FIS for the DEM survey called `2013610` as this is the only DEM survey that I've fixed the roughness associated raster.

```
Membership function bounds (0.430862831858407 1.01) do not fit in the set range (0) for this object.
 --- Stacktrace --- 
   at GCDConsoleLib.FIS.MemberFunctionSet.addMF(String sName, MemberFunction mf) in D:\Code\gcd\gcd\GCDConsoleLib\FIS\MemberFunctionSet.cs:line 70
   at GCDConsoleLib.FIS.FisFile.parseInputOutput(List`1 sLines, Boolean isInput) in D:\Code\gcd\gcd\GCDConsoleLib\FIS\FisFile.cs:line 168
   at GCDConsoleLib.FIS.FisFile..ctor(FileInfo inputFn) in D:\Code\gcd\gcd\GCDConsoleLib\FIS\FisFile.cs:line 51
   at GCDConsoleLib.Internal.Operators.FISRasterOp..ctor(Dictionary`2 rInputs, FileInfo fisFile) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\FISRasterOp.cs:line 36
   at GCDConsoleLib.Internal.Operators.CreateErrorRaster..ctor(Raster rawDEM, ErrorRasterProperties prop, Raster rOutputRaster) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\CreateErrorRaster.cs:line 43
   at GCDConsoleLib.RasterOperators.CreateErrorRaster(Raster rawDEM, ErrorRasterProperties props, FileInfo sOutputRaster, EventHandler`1 progressHandler) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 426
   at GCDCore.UserInterface.SurveyLibrary.frmErrorSurfaceProperties.btnOK_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd\GCDCore\UserInterface\SurveyLibrary\frmErrorSurfaceProperties.cs:line 652
Windows: Microsoft Windows NT 6.2.9200.0
Date: 1/30/2018 12:45:18 PM
```

**Comment by philipbaileynar** [comment]
I suspect this is related to issue #27

**Comment by philipbaileynar** [comment]
@MattReimer this is still occurring with the latest and greatest code as of today. 

I've created a GCD project today and added the one DEM survey and associated surfaces. These files, together with the custom FIS rule file are in the following zip:

```
Dump\2018_02_16_Grilliot.zip
```

**Comment by philipbaileynar** [comment]
Tested today with the fixes by @MattReimer and also the new user error surface user interface. Somewhat hard to know if this fixes James' original issue, but certainly worth closing this issue and starting our testing of error generation from scratch as we prepare for the workshop.
