### ISSUE TITLE
Error Importing DEM survey

### ISSUE THREAD

**Issue by josebeya** [Riverscapes/gcd#385]
Hi Phil,
Finally, after RCEM 2019 workshop I am getting my head around the GCD tools. I have created DEMs from our Lidar data following this process:

1) Get Terrain models created by our corporate GIS team from Lidar data
2) Clip and create rasters from those using a customized toolbox
3) Convert the raster to Geotiff following the advise on this forum after getting the error message "Error Importing DEM survey" when trying to import the rasters directly by selecting them from the Geodatabase.

After all these steps I still get the same error but the exception message has changed when trying different files and output raster accuracies. Also I noticed that when creating the Geotiff the raster resolution decreases which is undesirable.

Then I tried loading the rasters (tiff files) provided during the workshop and I got the same error. The exception message below is what I get when trying to load the file 'Feshie20061m.tif' used in the workshop. 

## Exception message

Object reference not set to an instance of an object.
 --- Stacktrace --- 
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.PerformRasterPyramids(FileInfo sRasterPath)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.ProcessRaster()
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.5.1.7333
GCD = 7.4.3.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 7/07/2020 9:54:45 AM
##

It looks like I may have an installation problem? I did use the same computer (Virtual Machine) in the workshop but I had to add the Add-Ins again because for the workshop the Add-Ins was copied into the downloads folder which was cleared later (I think).

Could you please advice?
[Feshie_2006_1m.zip](https://github.com/Riverscapes/gcd/files/4881434/Feshie_2006_1m.zip)

**Comment by philipbaileynar** [comment]
@josebeya I think you do have an installation problem. I downloaded the zip you attached to this issue. I created a new GCD project and added the raster from your zip file. No problems!

I suggest a full [uninstall](http://gcd.riverscapes.xyz/Download/install.html#uninstall) and re-install. Make sure you uninstall the AddIn within ArcGIS first. Then close all ESRI products. Uninstall the GCD standalone if you have that installed. Then re-install the GCD ArcGIS AddIn. 

Comment back here if that doesn't solve your problem.

![image](https://user-images.githubusercontent.com/8645379/92953882-570b3980-f417-11ea-8f34-4e8811198b82.png)
