### ISSUE TITLE
Error message "Root element missing"

### ISSUE THREAD

**Issue by dfieman** [Riverscapes/gcd#386]
## The Problem

What went wrong?

I want to create an error surface from the slope degrees associated surface. I cannot check the box beside FIS error model in the Create Error Surface for Entire DEM Extent.  The fuzzy inference system library is all there. However, when I try clicking  on options under the customize menu an error message "Root element is missing occurs". 

## Reproduction steps

1. Added Slope Degrees Associated Surface
2. Calculate Error Surface for Entire DEM Extent
3. FIS error model cannot be clicked on
4. Under 'Customize' and 'FIS Inference Library', all FIS files are there
5. Error message when clicking on 'Options' under 'Customize' 

## Exception message

Root element is missing.
 --- Stacktrace --- 
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at GCDCore.Project.SurveyType.Load(FileInfo filePath)
   at GCDCore.UserInterface.Options.frmOptions..ctor()
   at GCDStandalone.frmMain.optionsToolStripMenuItem_Click(Object sender, EventArgs e)
 --- Exception Data --- 
GCD = 7.5.0.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 27/07/2020 4:25:43 PM

```text

Paste the exception message you are getting from the app here. It really helps us. 

```

## Anything else?

You can attach links to datasets.

**Comment by joewheaton** [comment]
Have you tried calculating the slope surface instead of adding? Sometimes slope degrees are better as range is 0 to 90 whereas the upper limit on slope analyses in percent is a function of local relief and cell resolution. It could also be a problem with your FIS file you are customizing. You can attach the *.fis here and we can take a look..
