### ISSUE TITLE
Error importing Survey

### ISSUE THREAD

**Issue by mfmo45** [Riverscapes/gcd#389]
## The Problem
I am getting the following error message when I try to import a Survey DEM into ArcGIS 10.4: 

What went wrong?

## Reproduction steps

I created a new GCD file and saved it in a folder in my desktop. I selected a .tif DEM (created with ArcGIS) and the following error message appears. 

## Exception message
------------------------------------------------
EXCEPTION
The type initializer for 'GCDConsoleLib.GdalConfiguration' threw an exception.
 --- Stacktrace --- 
   at GCDConsoleLib.GdalConfiguration.ConfigureGdal()
   at GCDConsoleLib.Raster.Open(Boolean write) in D:\Code\gcd\gcd\GCDConsoleLib\Raster.cs:line 329
   at GCDConsoleLib.Raster._initfromfile() in D:\Code\gcd\gcd\GCDConsoleLib\Raster.cs:line 186
   at GCDConsoleLib.GISDataset.get_Proj() in D:\Code\gcd\gcd\GCDConsoleLib\GISDataset.cs:line 19
   at GCDCore.UserInterface.SurveyLibrary.GISDatasetValidation.DSHasSpatialRef(GISDataset gisDS, String sTypeSingle, String sTypePlural)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.PrepareToImportRaster(Surface refSurface, Purposes purpose, String Noun, IntPtr parentWindow)
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.4.0.5524
GCD = 7.5.0.0------------------------------------------------
EXCEPTION
The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
 --- Stacktrace --- 
   at OSGeo.GDAL.GdalPINVOKE.SetConfigOption(String jarg1, String jarg2)
   at OSGeo.GDAL.Gdal.SetConfigOption(String pszKey, String pszValue)
   at GCDConsoleLib.GdalConfiguration..cctor() in D:\Code\gcd\gcd\GCDConsoleLib\Utility\GdalConfiguration.cs:line 83------------------------------------------------
EXCEPTION
The type initializer for 'SWIGExceptionHelper' threw an exception.
 --- Stacktrace --- 
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
   at OSGeo.GDAL.GdalPINVOKE..cctor()Unable to load DLL 'gdal_wrap': No se encontró el proceso especificado. (Exception from HRESULT: 0x8007007F)
 --- Stacktrace --- 
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
Windows: Microsoft Windows NT 6.2.9200.0
Date: 08-Oct-20 3:35:39 PM
```text

Paste the exception message you are getting from the app here. It really helps us. 

```

## Anything else?
What can I do to solve this error or what does this error mean? 
You can attach links to datasets.

**Comment by philipbaileynar** [comment]
Does your raster load normally when you add it to ArcMap using the regular add data button?

Is there any way you can upload it somewhere and send a link?
