### ISSUE TITLE
Error Importing DEM Survey

### ISSUE THREAD

**Issue by tweddale** [Riverscapes/gcd#392]
## The Problem

Was unable to import a 2cm resolution Digital Surface Model for approx. 140acres.   Large file!

## Reproduction steps
1.  I ran import DEM Survey
2.  It ran to 91% completion and then threw error

## Exception message

------------------------------------------------
EXCEPTION
Exception has been thrown by the target of an invocation.
 --- Stacktrace --- 
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at GCDConsoleLib.RasterOperators.GenericRunWithOutput(Type generic, Type innerType, String sDesc, EventHandler`1 progressHandler, Object[] args) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 1293
   at GCDConsoleLib.RasterOperators.BilinearResample(Raster rInput, FileInfo sOutputRaster, ExtentRectangle outputExtent, EventHandler`1 progressHandler) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 391
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.ProcessRaster()
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.7.0.10450
GCD = 7.4.4.0TIFFAppendToStrip:Maximum TIFF file size exceeded. Use BIGTIFF=YES creation option.
 --- Stacktrace --- 
   at OSGeo.GDAL.Dataset.FlushCache()
   at GCDConsoleLib.Raster.Write[T](Int32 xOff, Int32 yOff, Int32 xSize, Int32 ySize, T[] buffer) in D:\Code\gcd\gcd\GCDConsoleLib\Raster.cs:line 688
   at GCDConsoleLib.Internal.Operators.BilinearResample`1.Run() in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\BilinearResample.cs:line 79
   at GCDConsoleLib.Internal.Operators.BilinearResample`1.RunWithOutput() in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\BilinearResample.cs:line 134
Windows: Microsoft Windows NT 6.2.9200.0
Date: 1/26/2021 9:55:41 AM

Paste the exception message you are getting from the app here. It really helps us. 

```

## Anything else?

You can attach links to datasets.

**Comment by philipbaileynar** [comment]
You can see from the error message that the maximum TIFF file size has been exceeded. We don't have a solution for this at this time. Perhaps try splitting your raster into two or more smaller files.

```
TIFFAppendToStrip:Maximum TIFF file size exceeded. Use BIGTIFF=YES creation option.
```
@MattReimer this might be a flag that we can apply judiciously.
