### ISSUE TITLE
Value was either too large or too small for a Decimal

### ISSUE THREAD

**Issue by akasprak** [Riverscapes/gcd#399]
## The Problem

Exception titled "Value was either too large or too small for a Decimal" when performing simple minLoD change detection. 

## Reproduction steps

1. Created new GCD project
2. Added the old DEM, 'dem_1.tif' to the project
3. Added the new DEM, 'dem_2.tif' to the project
4. Performed change detection with the two DEMs specified above and generated the exception below.

## Exception message

```text

Value was either too large or too small for a Decimal.
 --- Stacktrace --- 
   at System.Decimal..ctor(Double value)
   at GCDConsoleLib.Histogram.BinId(Double val) in D:\Code\gcd\gcd\GCDConsoleLib\Histogram.cs:line 205
   at GCDConsoleLib.Histogram.AddBinVal(Double val) in D:\Code\gcd\gcd\GCDConsoleLib\Histogram.cs:line 222
   at GCDConsoleLib.Internal.Operators.BinRaster.CellOp(List`1 data, List`1 outputs, Int32 id) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\BinRaster.cs:line 132
   at GCDConsoleLib.Internal.CellByCellOperator`1.ChunkOp(List`1 data, List`1 outChunks) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\CellByCellOperator.cs:line 90
   at GCDConsoleLib.Internal.BaseOperator`1.Run() in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 417
   at GCDConsoleLib.RasterOperators.BinRaster(Raster rInput, Int32 numberofBins, EventHandler`1 progressHandler) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 766
   at GCDCore.Engines.ChangeDetectionEngineBase.Calculate(String dodName, DirectoryInfo analysisFolder, Boolean bBuildPyramids, UnitGroup units)
   at GCDCore.UserInterface.ChangeDetection.frmDoDProperties.cmdOK_Click(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.8.1.14362
GCD = 7.5.0.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 6/7/2021 3:17:29 PM

```

## Anything else?
There are many cells with NoData in the rasters, this is intentional.

Link to the above files:
https://fortlewiscollege-my.sharepoint.com/:f:/g/personal/akasprak_fortlewis_edu/EoL1ja_rxhNDg6XOzcHtl1oBFXxqBpV40x3Mi3osGxgu7A?e=orr1P1

I'm able to perform this change detection in raster calculator. The vertical and volumetric magnitudes of change are quite small (i.e., < +/-10 cm vertical change). I've tried setting the units in the GCD project to m2/m3 and cm2/cm3, but both approaches produce this error. I've also ensured that NoData is set to the appropriate value (3.40282346639e+38). I've used a variety of minLoD thresholds (0.001, 0.01, the default of 0.2), to no avail.

**Comment by philipbaileynar** [comment]
Hi Alan,

This sure sounds like a problematic NoData problem. It's as if the NoData in the raster properties is ever so slightly different than the value being stored in the cells themselves. If the NoData extents are slightly different for different DEM surveys GCD will attempt math on cells with very large or very small values, causing a floating point wrap around.

We don't have any GCD funding to address this issue at this time. But here's something you might try...

Use the Raster Calculator or SetNull tool to set all raster values that are less than the known range of reasonable values to NoData. Then repeat for the upper range.  So if the raster data range is say 100.000 to 1000.1234, I would set everything less than 100 to NoData and everything larger than 1001 to NoData. Repeat the process for each DEM survey. Then attempt DoD again.

Post back here the results of the test. Good luck.

**Comment by akasprak** [comment]
Nice, Philip - that one worked for me. The rasters were originally multi-band ENVI format, and somewhere in the conversion to single-band .tif rasters in Arc, the NoData value must not have come through correctly. No worries on the funding at the moment! In the future, I wonder if GCD could check for consistency in NoData values between DEMs when performing a change detection (although it may already do that, just not to a crazy amount of decimal places). Thanks again!

Alan
