### ISSUE TITLE
Error Creating Interpolation Error Surface

### ISSUE THREAD

**Issue by mskinner01** [Riverscapes/gcd#404]
## The Problem

I am trying to create an interpolation error surface but when I go to run it I get an error message that says  "Unhandled exception has occurred in a component in your application. If you click Continue, the application will ignore this error and attempt to continue. Object reference not set to an instance of an object."

## Reproduction steps

1. I added all of the needed inputs and double checked to make sure all of the projections matched.
2. Then I tried to ignore the error by pressing Continue but it was still unable to run.

## Error message

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at TATAddin.GISCode.WorkspaceManager.GetTempShapeFile(String sRootName) in D:\Code\gcd\tat-addin\TATAddin\GISCode\General\WorkspaceManager.vb:line 42
   at TATAddin.ErrorGenerator_InterpolationError.ExecuteUI(String sOutputRaster, String sZFieldName) in D:\Code\gcd\tat-addin\TATAddin\GISCode\GCD\ErrorCalculation\ErrorGenerator_InterpolationError.vb:line 123
   at TATAddin.frm_InterploationError.btn_Run_Click(Object sender, EventArgs e) in D:\Code\gcd\tat-addin\TATAddin\Experimental\UncertaintyAnalysis\frm_InterploationError.vb:line 167
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ESRI.DADF.Core
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.7/bin/ESRI.DADF.Core.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ESRI.APWR.ApFramework
    Assembly Version: 1.0.0.0
    Win32 Version: 10.2.0.7
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/ESRI.APWR.ApFramework/1.0.0.0__0e46c6306d55f57a/ESRI.APWR.ApFramework.dll
----------------------------------------
ESRI.ArcGIS.System
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.System/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.System.dll
----------------------------------------
ESRI.ArcGIS.Display
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Display/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Display.dll
----------------------------------------
ESRI.ArcGIS.Carto
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Carto/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Carto.dll
----------------------------------------
ESRI.ArcGIS.Geodatabase
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Geodatabase/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Geodatabase.dll
----------------------------------------
ESRI.ArcGIS.Geometry
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Geometry/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Geometry.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
ESRI.ArcGIS.Desktop.AddIns.Factory
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.7/bin/ESRI.ArcGIS.Desktop.AddIns.Factory.DLL
----------------------------------------
ESRI.ArcGIS.Desktop.AddIns
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.7/bin/ESRI.ArcGIS.Desktop.AddIns.DLL
----------------------------------------
ESRI.ArcGIS.Framework
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Framework/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Framework.dll
----------------------------------------
ESRI.ArcGIS.ArcMapUI
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.ArcMapUI/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.ArcMapUI.dll
----------------------------------------
GCDAddIn
    Assembly Version: 7.5.0.0
    Win32 Version: 7.5.0.0
    CodeBase: file:///C:/Users/student/AppData/Local/ESRI/Desktop10.7/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/GCDAddIn.dll
----------------------------------------
GCDCore
    Assembly Version: 7.5.0.0
    Win32 Version: 7.5.0.0
    CodeBase: file:///C:/Users/student/AppData/Local/ESRI/Desktop10.7/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/GCDCore.DLL
----------------------------------------
GCDConsoleLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/student/AppData/Local/ESRI/Desktop10.7/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/GCDConsoleLib.DLL
----------------------------------------
naru
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/student/AppData/Local/ESRI/Desktop10.7/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/naru.DLL
----------------------------------------
ESRI.ArcGIS.SearchUI
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.7/bin/ESRI.ArcGIS.SearchUI.DLL
----------------------------------------
ESRI.ArcGIS.SearchControl
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.7/bin/ESRI.ArcGIS.SearchControl.DLL
----------------------------------------
ESRI.ArcGIS.SearchCore
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.7/bin/ESRI.ArcGIS.SearchCore.DLL
----------------------------------------
ESRI.ArcGIS.Search
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Search/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Search.dll
----------------------------------------
ESRI.ArcGIS.SystemUI
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.SystemUI/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.SystemUI.dll
----------------------------------------
ESRI.ArcGIS.Version
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Version/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Version.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
ESRI.ArcGIS.Geoprocessing
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Geoprocessing/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Geoprocessing.dll
----------------------------------------
GpMetadataFunctions
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.7/bin/GpMetadataFunctions.DLL
----------------------------------------
System.Data.SqlXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
System.Xml.Xsl.CompiledQuery.1
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
Lucene.Net
    Assembly Version: 2.9.2.1
    Win32 Version: 2.9.2.1
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Lucene.Net/2.9.2.1__402f1553d5c332e7/Lucene.Net.dll
----------------------------------------
Snowball.Net
    Assembly Version: 2.0.0.1
    Win32 Version: 2.0.0.1
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Snowball.Net/2.0.0.1__402f1553d5c332e7/Snowball.Net.dll
----------------------------------------
ESRI.ArcGIS.Editor
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Editor/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Editor.dll
----------------------------------------
ESRI.ArcGIS.MxCommands
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.7/bin/ESRI.ArcGIS.MxCommands.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
ESRI.ArcGIS.MapCenter
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/Users/student/AppData/Local/ESRI/Desktop10.7/AssemblyCache/%7B75701328-F0CC-4E65-B204-99944EDF5B93%7D/ESRI.ArcGIS.MapCenter.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
ESRI.ArcGIS.ArcGlobe
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.ArcGlobe/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.ArcGlobe.dll
----------------------------------------
ESRI.ArcGIS.ArcScene
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.ArcScene/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.ArcScene.dll
----------------------------------------
UnitsNet
    Assembly Version: 3.77.0.0
    Win32 Version: 3.77.0.0
    CodeBase: file:///C:/Users/student/AppData/Local/ESRI/Desktop10.7/AssemblyCache/%7BF8CA7DEA-22FB-40A3-8412-B84A4B528602%7D/UnitsNet.DLL
----------------------------------------
TATAddin
    Assembly Version: 1.0.2.0
    Win32 Version: 1.0.2.0
    CodeBase: file:///C:/Users/student/AppData/Local/ESRI/Desktop10.7/AssemblyCache/%7B6726F1A0-44DA-40CF-B66B-797CAD31736B%7D/TATAddin.dll
----------------------------------------
ESRI.ArcGIS.CatalogUI
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.CatalogUI/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.CatalogUI.dll
----------------------------------------
ESRI.ArcGIS.Catalog
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Catalog/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Catalog.dll
----------------------------------------
ESRI.ArcGIS.DataSourcesRaster
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.DataSourcesRaster/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.DataSourcesRaster.dll
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
ESRI.ArcGIS.GlobeCore
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.GlobeCore/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.GlobeCore.dll
----------------------------------------
ESRI.ArcGIS.3DAnalyst
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.3DAnalyst/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.3DAnalyst.dll
----------------------------------------
ESRI.ArcGIS.Controls
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.Controls/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.Controls.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
ESRI.ArcGIS.GeoprocessingUI
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.GeoprocessingUI/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.GeoprocessingUI.dll
----------------------------------------
ESRI.ArcGIS.Client.Local.Private
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.3152
    CodeBase: file:///C:/Program%20Files%20(x86)/ArcGIS/Desktop10.7/bin/ESRI.ArcGIS.Client.Local.Private.DLL
----------------------------------------
System.ServiceModel.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Web/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Web.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
ESRI.ArcGIS.DataSourcesFile
    Assembly Version: 10.7.0.0
    Win32 Version: 10.7.0.10450
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/ESRI.ArcGIS.DataSourcesFile/v4.0_10.7.0.0__8fc3cc631e44ad86/ESRI.ArcGIS.DataSourcesFile.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

## Anything else?

What is a Point Cloud Shapefile? I have tried adding various shapefiles of the data points that contain the xyz data as well as point clouds but wanted to check and see if a Point Cloud Shapefile is a different type of file and causing the issue.

**Comment by mskinner01** [comment]
I am trying to make a FIS Error Surface again but now when I try and run it I get a system load exception message. I have deleted and redownloaded the add-in but the problem persists.
