### ISSUE TITLE
Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)

### ISSUE THREAD

**Issue by TimPoate** [Riverscapes/gcd#418]
Getting an error during change detection creation

What went wrong?

Loaded two .tif DEMs, both same area temporally spaced. Added Error values
Went to Create Change Detection- 

Exception has been thrown by the target of an invocation

EXCEPTION
Exception has been thrown by the target of an invocation.
 --- Stacktrace --- 
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at GCDConsoleLib.RasterOperators.GenericRunWithOutput(Type generic, Type innerType, String sDesc, EventHandler`1 progressHandler, Object[] args)
   at GCDConsoleLib.RasterOperators.Subtract(Raster rInputA, Raster rInputB, FileInfo sOutputRaster, EventHandler`1 progressHandler)
   at GCDCore.Engines.ChangeDetectionEngineBase.Calculate(String dodName, DirectoryInfo analysisFolder, Boolean bBuildPyramids, UnitGroup units)
   at GCDCore.UserInterface.ChangeDetection.frmDoDProperties.cmdOK_Click(Object sender, EventArgs e)
 --- Exception Data --- 
GCD = 7.5.0.0Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
 --- Stacktrace --- 
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at GCDConsoleLib.Internal.Operators.RasterMath`1.CellOp(List`1 data, List`1 outputs, Int32 id)
   at GCDConsoleLib.Internal.CellByCellOperator`1.ChunkOp(List`1 data, List`1 outChunks)
   at GCDConsoleLib.Internal.BaseOperator`1.Run()
   at GCDConsoleLib.Internal.BaseOperator`1.RunWithOutput()
Windows: Microsoft Windows NT 6.2.9200.0
Date: 13/10/2021 22:40:12

```
Any suggestions on error cause?
Cheers

**Comment by philipbaileynar** [comment]
How did you provide error values?

- Uniform value?
- Imported error raster?
- FIS?

How big are the rasters? Are you able to zip and get your project to me?
