### ISSUE TITLE
Error Importing DEM Survey

### ISSUE THREAD

**Issue by trice1996** [Riverscapes/gcd#420]
## The Problem
I ran into an error importing my DEM's
What went wrong?
The first step in calculating a DoD and I ran into an error importing the DEM's I made in ArcGIS using the tutorial
## Exception message

```text

Paste the exception message you are getting from the app here. It really helps us. 
Object reference not set to an instance of an object.
 --- Stacktrace --- 
   at GCDCore.UserInterface.SurveyLibrary.GISDatasetValidation.DSHasSpatialRef(GISDataset gisDS, String sTypeSingle, String sTypePlural)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.PrepareToImportRaster(Surface refSurface, Purposes purpose, String Noun, IntPtr parentWindow)
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.8.1.14362
GCD = 7.5.0.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 11/3/2021 11:19:41 AM
```

## Anything else?

You can attach links to datasets.

**Comment by philipbaileynar** [comment]
Make sure your input DEMs are in floating point GeoTiff format.

**Comment by trice1996** [comment]
I used the Copy Raster tool to export the raster as a 32-bit optimized GeoTIFF and it still isn't uploading correctly. Are there more settings I'm missing?

**Comment by philipbaileynar** [comment]
Can you zip the DEM. If it's small you can attach it to this ticket. If it's too big you might need to put it somewhere public on the internet and link to it here.

**Comment by trice1996** [comment]
[Apr21_DEM.zip](https://github.com/Riverscapes/gcd/files/8744779/Apr21_DEM.zip)

**Comment by philipbaileynar** [comment]
It looks like the file didn't upload correctly.
