### ISSUE TITLE
Error adding DEM Surveys

### ISSUE THREAD

**Issue by turnsgirl310** [Riverscapes/gcd#429]
I am working on trying to add DEM to my GCD Project. I keep getting this error and don't know what to do.
I have checked it is in floating point
It has a spatial reference. 
Please help!

EPSG PCS/GCS code 6360 not found in EPSG support files.  Is this a valid EPSG coordinate system?
 --- Stacktrace --- 
   at OSGeo.GDAL.Dataset.GetProjection()
   at GCDConsoleLib.Raster._initfromfile() in D:\Code\gcd\gcd\GCDConsoleLib\Raster.cs:line 186
   at GCDConsoleLib.GISDataset.get_Proj() in D:\Code\gcd\gcd\GCDConsoleLib\GISDataset.cs:line 19
   at GCDCore.UserInterface.SurveyLibrary.GISDatasetValidation.DSHasSpatialRef(GISDataset gisDS, String sTypeSingle, String sTypePlural)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.PrepareToImportRaster(Surface refSurface, Purposes purpose, String Noun, IntPtr parentWindow)
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.7.0.10450
GCD = 7.5.0.0

**Comment by joewheaton** [comment]
@turnsgirl310 provide a link to data or video please. Pretty difficult to troubleshoot based on what you provided...
