### ISSUE TITLE
Error importing DEM survey, EPSG code not found in EPSG supported files 

### ISSUE THREAD

**Issue by davidpp9** [Riverscapes/gcd#441]
When trying to import DEMs I get following error: 

EPSG PCS/GCS code 6647 not found in EPSG support files.  Is this a valid EPSG coordinate system?
 --- Stacktrace --- 
   at OSGeo.GDAL.Band.GetUnitType()
   at GCDConsoleLib.Raster._initfromfile() in D:\Code\gcd\gcd\GCDConsoleLib\Raster.cs:line 186
   at GCDConsoleLib.GISDataset.get_Proj() in D:\Code\gcd\gcd\GCDConsoleLib\GISDataset.cs:line 19
   at GCDCore.UserInterface.SurveyLibrary.GISDatasetValidation.DSHasSpatialRef(GISDataset gisDS, String sTypeSingle, String sTypePlural)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.PrepareToImportRaster(Surface refSurface, Purposes purpose, String Noun, IntPtr parentWindow)
   at GCDCore.UserInterface.Project.TreeNodeTypes.DEMSurveysGroup.OnAdd(Object sender, EventArgs e)
 --- Exception Data --- 
ArcMap = 10.8.1.14362
GCD = 7.5.0.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 2023-03-06 3:33:11 PM

The error tells me that the vertical coordinate system EPSG 6647 is not supported. Does it have to re-projected in a different vertical coordinate system? What vertical coordinate systems are supported? 

Thanks!
David

**Comment by philipbaileynar** [comment]
https://spatialreference.org/ref/sr-org/6647/
