### ISSUE TITLE
Single method FIS not working

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/gcd#7]
Trying to run single method FIS using the attached inputs and getting the following error.

[FISInputs.zip](https://github.com/Riverscapes/gcd/files/1532447/FISInputs.zip)

```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
 --- Stacktrace --- 
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at GCDConsoleLib.FIS.RuleSet.calculate(List`1 dataArrays, Int32 n, Boolean checkNoData, List`1 noDataValues, Double noData) in D:\Code\gcd\gcd\GCDConsoleLib\FIS\RuleSet.cs:line 226
   at GCDConsoleLib.Internal.Operators.FISRasterOp.FISCellOp(List`1 data, Int32 id) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\FISRasterOp.cs:line 59
   at GCDConsoleLib.Internal.Operators.CreateErrorRaster.CellChangeCalc(String propkey, List`1 data, Int32 id) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\CreateErrorRaster.cs:line 94
   at GCDConsoleLib.Internal.Operators.CreateErrorRaster.CellOp(List`1 data, Int32 id) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Operators\CreateErrorRaster.cs:line 133
   at GCDConsoleLib.Internal.CellByCellOperator`1.ChunkOp(List`1 data, T[] outChunk) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\CellByCellOperator.cs:line 33
   at GCDConsoleLib.Internal.BaseOperator`1.Run() in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 200
   at GCDConsoleLib.Internal.BaseOperator`1.RunWithOutput() in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\BaseOperator.cs:line 221
   at GCDConsoleLib.RasterOperators.CreateErrorRaster(Raster rawDEM, ErrorRasterProperties props, FileInfo sOutputRaster, EventHandler`1 progressHandler) in D:\Code\gcd\gcd\GCDConsoleLib\RasterOperators\Interfaces.cs:line 424
   at GCDCore.UserInterface.SurveyLibrary.frmErrorSurfaceProperties.btnOK_Click(Object sender, EventArgs e) in D:\Code\gcd\gcd\GCDCore\UserInterface\SurveyLibrary\frmErrorSurfaceProperties.cs:line 628
Windows: Microsoft Windows NT 6.2.9200.0
Date: 12/5/2017 10:36:10 AM
```

**Comment by MattReimer** [comment]
@philipbaileynar I get a decent raster when I tried it with your inputs. I think you may not be feeding the function correctly. Let's go over it when you have a minute
